/* 
 * Versão para SQLite
 * 02/10/2021 - Autor: Alex Vinicius
 * Inserindo Categorias
*/

PRAGMA temp_store = 2; /* 2 means use in-memory */
CREATE TEMP TABLE IF NOT EXISTS _Categorias (Descricao TEXT, DescricaoSemAcento TEXT);
-- Clean up
DELETE FROM _Categorias;
/* Declaring a variable */
INSERT INTO _Categorias (Descricao, DescricaoSemAcento) VALUES
('Física', 'FISICA'),
('Utensílios', 'UTENSILIOS'),
('Livros', 'LIVROS'),
('Filmes', 'FILMES'),
('Química', 'QUIMICA'),
('Ditados', 'DITADOS'),
('Alimentos', 'ALIMENTOS'),
('Mitologia', 'MITOLOGIA'),
('Animais', 'ANIMAIS'),
('Esportes', 'ESPORTES'),
('Corpo Humano', 'CORPOHUMANO'),
('Geografia', 'GEOGRAFIA'),
('Sinônimos', 'SINONIMOS'),
('Inglês', 'INGLES'),
('Espanhol', 'ESPANHOL'),
('Francês', 'FRANCES');

-- Incluir pelo menos 1 item caso tabela estiver vazia
INSERT INTO Categorias (Descricao, DescricaoSemAcento)
SELECT 'Física', 'FISICA'
WHERE NOT EXISTS (
	SELECT 1 FROM Categorias 
	WHERE Descricao = 'Física' AND DescricaoSemAcento = 'FISICA'
);

-- Atualizar campo DescricaoSemAcento
UPDATE Categorias 
SET DescricaoSemAcento = (SELECT t.DescricaoSemAcento FROM _Categorias t WHERE t.Descricao = Categorias.Descricao);

-- Inserindo valores
INSERT INTO Categorias (Descricao, DescricaoSemAcento)
SELECT Descricao, DescricaoSemAcento
FROM _Categorias
EXCEPT
SELECT Descricao, DescricaoSemAcento
FROM Categorias;

--------------------------------------------------------------------
-- Trecho para adicionar palavras
CREATE TEMP TABLE IF NOT EXISTS _Palavras (Valor TEXT, ValorSemAcento TEXT, Dica TEXT, DicaSemAcento TEXT, Categoria TEXT);
-- Clean up
DELETE FROM _Palavras;

INSERT INTO _Palavras (Dica, DicaSemAcento, Valor, ValorSemAcento, Categoria) VALUES
('Medida dinâmica, igual ao trabalho de 75 quilogrâmetros por segundo', 'MEDIDA DINAMICA, IGUAL AO TRABALHO DE 75 QUILOGRAMETROS POR SEGUNDO', 'Cavalo vapor', 'CAVALO VAPOR', 'FISICA'),
('Grande quantidade de estrelas', 'GRANDE QUANTIDADE DE ESTRELAS', 'Galáxia', 'GALAXIA', 'FISICA'),
('Um padrão reconhecível de estrelas no céu', 'UM PADRAO RECONHECIVEL DE ESTRELAS NO CEU', 'Constelação', 'CONSTELACAO', 'FISICA'),
('A energia potencial elétrica é medida em', 'A ENERGIA POTENCIAL ELETRICA E MEDIDA EM', 'Joules', 'JOULES', 'FISICA'),
('Inventado por Alexander Graham Bell', 'INVENTADO POR ALEXANDER GRAHAM BELL', 'Telefone', 'TELEFONE', 'FISICA'),
('Inventado por Thomas Edison', 'INVENTADO POR THOMAS EDISON', 'Lâmpada', 'LAMPADA', 'FISICA'),
('Nikola Tesla desenvolveu o sistema de distribuição de corrente elétrica', 'NIKOLA TESLA DESENVOLVEU O SISTEMA DE DISTRIBUICAO DE CORRENTE ELETRICA', 'Trifásico', 'TRIFASICO', 'FISICA'),
('Wilhem Röntgen descobriu a existência dos raios', 'WILHEM RONTGEN DESCOBRIU A EXISTENCIA DOS RAIOS', 'X', 'X', 'FISICA'),
('Antoine Becquerel descobriu a existência da', 'ANTOINE BECQUEREL DESCOBRIU A EXISTENCIA DA', 'Radioatividade', 'RADIOATIVIDADE', 'FISICA'),
('O objeto do estudo da mecânica é o', 'O OBJETO DO ESTUDO DA MECANICA E O', 'Movimento', 'MOVIMENTO', 'FISICA'),
('Área da mecânica que estuda o movimento dos corpos', 'AREA DA MECANICA QUE ESTUDA O MOVIMENTO DOS CORPOS', 'Cinemática', 'CINEMATICA', 'FISICA'),
('Movimento em que a velocidade de um corpo é constante', 'MOVIMENTO EM QUE A VELOCIDADE DE UM CORPO E CONSTANTE', 'Uniforme', 'UNIFORME', 'FISICA'),
('Medida do grau de agitação das partículas que constituem um corpo', 'MEDIDA DO GRAU DE AGITACAO DAS PARTICULAS QUE CONSTITUEM UM CORPO', 'Temperatura', 'TEMPERATURA', 'FISICA'),
('Transmissão de calor mediante o contato de superfícies', 'TRANSMISSAO DE CALOR MEDIANTE O CONTATO DE SUPERFICIES', 'Condução', 'CONDUCAO', 'FISICA'),
('Transmissão de calor em razão da formação de correntes convectivas em um fluido', 'TRANSMISSAO DE CALOR EM RAZAO DA FORMACAO DE CORRENTES CONVECTIVAS EM UM FLUIDO', 'Convecção', 'CONVECCAO', 'FISICA'),
('Transmissão de calor por ondas eletromagnéticas', 'TRANSMISSAO DE CALOR POR ONDAS ELETROMAGNETICAS', 'Irradiação', 'IRRADIACAO', 'FISICA'),
('Primeira lei da Termodinâmica é a lei da', 'PRIMEIRA LEI DA TERMODINAMICA E A LEI DA', 'Conservação', 'CONSERVACAO', 'FISICA'),
('Segunda lei da Termodinâmica é a lei da', 'SEGUNDA LEI DA TERMODINAMICA E A LEI DA', 'Entropia', 'ENTROPIA', 'FISICA'),
('De cobre ou feito com cobre', 'DE COBRE OU FEITO COM COBRE', 'Cuprico', 'CUPRICO', 'QUIMICA'),
('Liga metálica de cobre e prata', 'LIGA METALICA DE COBRE E PRATA', 'Alpaca', 'ALPACA', 'QUIMICA'),
('Exemplo de composto orgânico', 'EXEMPLO DE COMPOSTO ORGANICO', 'Proteína', 'PROTEINA', 'QUIMICA'),
('Exemplo de composto orgânico', 'EXEMPLO DE COMPOSTO ORGANICO', 'Glicídio', 'GLICIDIO', 'QUIMICA'),
('Exemplo de composto orgânico', 'EXEMPLO DE COMPOSTO ORGANICO', 'Lipídio', 'LIPIDIO', 'QUIMICA'),
('Exemplo de composto orgânico', 'EXEMPLO DE COMPOSTO ORGANICO', 'Vitamina', 'VITAMINA', 'QUIMICA'),
('Exemplo de composto orgânico', 'EXEMPLO DE COMPOSTO ORGANICO', 'Enzima', 'ENZIMA', 'QUIMICA'),
('Massa atômica (A) igual a 12', 'MASSA ATOMICA (A) IGUAL A 12', 'Carbono', 'CARBONO', 'QUIMICA'),
('Exemplo de composto formado de nitrogênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE NITROGENIO NA CADEIA CARBONICA', 'Amina', 'AMINA', 'QUIMICA'),
('Exemplo de composto formado de nitrogênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE NITROGENIO NA CADEIA CARBONICA', 'Amida', 'AMIDA', 'QUIMICA'),
('Exemplo de composto formado de nitrogênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE NITROGENIO NA CADEIA CARBONICA', 'Nitrila', 'NITRILA', 'QUIMICA'),
('Exemplo de composto formado de nitrogênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE NITROGENIO NA CADEIA CARBONICA', 'Nitrocomposto', 'NITROCOMPOSTO', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Aldeído', 'ALDEIDO', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Cetona', 'CETONA', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Ácido carboxílico', 'ACIDO CARBOXILICO', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Éster', 'ESTER', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Éter', 'ETER', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Fenól', 'FENOL', 'QUIMICA'),
('Exemplo de Composto formado de oxigênio na cadeia carbônica', 'EXEMPLO DE COMPOSTO FORMADO DE OXIGENIO NA CADEIA CARBONICA', 'Álcool', 'ALCOOL', 'QUIMICA'),
('Dor de cotovelo', 'DOR DE COTOVELO', 'Inveja', 'INVEJA', 'DITADOS'),
('Falar pelos cotovelos', 'FALAR PELOS COTOVELOS', 'Tagarelar', 'TAGARELAR', 'DITADOS'),
('Abotoar o paletó', 'ABOTOAR O PALETO', 'Morrer', 'MORRER', 'DITADOS'),
('Abrir mão de alguma coisa', 'ABRIR MAO DE ALGUMA COISA', 'Renunciar', 'RENUNCIAR', 'DITADOS'),
('Come cru e quente', 'COME CRU E QUENTE', 'Apressado', 'APRESSADO', 'DITADOS'),
('Conversa fiada', 'CONVERSA FIADA', 'Mentir', 'MENTIR', 'DITADOS'),
('Trocar alhos por bugalhos', 'TROCAR ALHOS POR BUGALHOS', 'Confundir', 'CONFUNDIR', 'DITADOS'),
('Riscar do mapa', 'RISCAR DO MAPA', 'Desaparecer', 'DESAPARECER', 'DITADOS'),
('Chato de galocha', 'CHATO DE GALOCHA', 'Desagradável', 'DESAGRADAVEL', 'DITADOS'),
('Pessoa mão na roda', 'PESSOA MAO NA RODA', 'Prestativo', 'PRESTATIVO', 'DITADOS'),
('Tirar água do joelho', 'TIRAR AGUA DO JOELHO', 'Urinar', 'URINAR', 'DITADOS'),
('Ficar dando sopa', 'FICAR DANDO SOPA', 'Vulnerável', 'VULNERAVEL', 'DITADOS'),
('Enxugar gelo', 'ENXUGAR GELO', 'Inutíl', 'INUTIL', 'DITADOS'),
('Pessoa com a cabeça nas nuvens', 'PESSOA COM A CABECA NAS NUVENS', 'Distraído', 'DISTRAIDO', 'DITADOS'),
('Babar ovo de alguém', 'BABAR OVO DE ALGUEM', 'Idolatrar', 'IDOLATRAR', 'DITADOS'),
('Arrumar sarna para se coçar', 'ARRUMAR SARNA PARA SE COCAR', 'Problema', 'PROBLEMA', 'DITADOS'),
('Fruto de pele aveludada', 'FRUTO DE PELE AVELUDADA', 'Pêssego', 'PESSEGO', 'ALIMENTOS'),
('Um dos formatos em que se come bacalhau', 'UM DOS FORMATOS EM QUE SE COME BACALHAU', 'Bolinho', 'BOLINHO', 'ALIMENTOS'),
('Peixe considerado o bacalhau da Amazônia', 'PEIXE CONSIDERADO O BACALHAU DA AMAZONIA', 'Pirarucu', 'PIRARUCU', 'ALIMENTOS'),
('Fruto típico da região norte do Brasil', 'FRUTO TIPICO DA REGIAO NORTE DO BRASIL', 'Cupuaçu', 'CUPUACU', 'ALIMENTOS'),
('Muito popular tanto na Argentina como no Uruguai', 'MUITO POPULAR TANTO NA ARGENTINA COMO NO URUGUAI', 'Parrillada', 'PARRILLADA', 'ALIMENTOS'),
('Considerado prato nacional da Grécia', 'CONSIDERADO PRATO NACIONAL DA GRECIA', 'Moussaka', 'MOUSSAKA', 'ALIMENTOS'),
('o Pad Thai  da Tailândia é servido com frutos do mar e ...', 'O PAD THAI  DA TAILANDIA E SERVIDO COM FRUTOS DO MAR E ...', 'Camarão', 'CAMARAO', 'ALIMENTOS'),
('Tradicional prato da Turquia consumido no café da manhã', 'TRADICIONAL PRATO DA TURQUIA CONSUMIDO NO CAFE DA MANHA', 'Menemen', 'MENEMEN', 'ALIMENTOS'),
('Receita francesa clássica onde os ingredientes principais são berinjela e tomate', 'RECEITA FRANCESA CLASSICA ONDE OS INGREDIENTES PRINCIPAIS SAO BERINJELA E TOMATE', 'Ratatouille', 'RATATOUILLE', 'ALIMENTOS'),
('Espécie de sopa feita de milho, tradicional da culinária do México', 'ESPECIE DE SOPA FEITA DE MILHO, TRADICIONAL DA CULINARIA DO MEXICO', 'Pozole', 'POZOLE', 'ALIMENTOS'),
('Sopa muito consumida na Rússia e na Ucrânia', 'SOPA MUITO CONSUMIDA NA RUSSIA E NA UCRANIA', 'Borscht', 'BORSCHT', 'ALIMENTOS'),
('Prato à base de arroz, bem típico da gastronomia de Valência', 'PRATO A BASE DE ARROZ, BEM TIPICO DA GASTRONOMIA DE VALENCIA', 'Paella', 'PAELLA', 'ALIMENTOS'),
('Iguaria feita com chocolate e doce leite popular da Argentina', 'IGUARIA FEITA COM CHOCOLATE E DOCE LEITE POPULAR DA ARGENTINA', 'Alfajor', 'ALFAJOR', 'ALIMENTOS'),
('Considerado o prato nacional da Arábia Saudita', 'CONSIDERADO O PRATO NACIONAL DA ARABIA SAUDITA', 'Kabsa', 'KABSA', 'ALIMENTOS'),
('A sobremesa mais tradicional da Áustria', 'A SOBREMESA MAIS TRADICIONAL DA AUSTRIA', 'Apfelstrudel', 'APFELSTRUDEL', 'ALIMENTOS'),
('Prato originado em Quebec, mas popular em todo o Canadá', 'PRATO ORIGINADO EM QUEBEC, MAS POPULAR EM TODO O CANADA', 'Poutine', 'POUTINE', 'ALIMENTOS'),
('Rolinhos de peixe cru, arroz e algas japoneses', 'ROLINHOS DE PEIXE CRU, ARROZ E ALGAS JAPONESES', 'Sushi', 'SUSHI', 'ALIMENTOS'),
('Prato típico da cultura peruana', 'PRATO TIPICO DA CULTURA PERUANA', 'Ceviche', 'CEVICHE', 'ALIMENTOS'),
('Fruta proíbida o paraíso', 'FRUTA PROIBIDA O PARAISO', 'Maçã', 'MACA', 'ALIMENTOS'),
('Fruta do bombom caribe', 'FRUTA DO BOMBOM CARIBE', 'Banana', 'BANANA', 'ALIMENTOS'),
('Fruta que forma o sabor prestígio', 'FRUTA QUE FORMA O SABOR PRESTIGIO', 'Coco', 'COCO', 'ALIMENTOS'),
('Fruta de cor amarela', 'FRUTA DE COR AMARELA', 'Abacaxi', 'ABACAXI', 'ALIMENTOS'),
('Fruta de tamanho muito grande', 'FRUTA DE TAMANHO MUITO GRANDE', 'Melancia', 'MELANCIA', 'ALIMENTOS'),
('Fruta de cor alaranjada', 'FRUTA DE COR ALARANJADA', 'Laranja', 'LARANJA', 'ALIMENTOS'),
('Famosa fruta cítrica', 'FAMOSA FRUTA CITRICA', 'Limão', 'LIMAO', 'ALIMENTOS'),
('Pai do sol da lua e das estrelas na mitologia', 'PAI DO SOL DA LUA E DAS ESTRELAS NA MITOLOGIA', 'Hiperião', 'HIPERIAO', 'MITOLOGIA'),
('Senhor dos homens e supremo mandatário dos deuses do monte Olimpo', 'SENHOR DOS HOMENS E SUPREMO MANDATARIO DOS DEUSES DO MONTE OLIMPO', 'Zeus', 'ZEUS', 'MITOLOGIA'),
('Matou a Medusa', 'MATOU A MEDUSA', 'Perseu', 'PERSEU', 'MITOLOGIA'),
('Terrível criatura com cabeleira formada por serpentes', 'TERRIVEL CRIATURA COM CABELEIRA FORMADA POR SERPENTES', 'Medusa', 'MEDUSA', 'MITOLOGIA'),
('Matou o Minotauro', 'MATOU O MINOTAURO', 'Teseu', 'TESEU', 'MITOLOGIA'),
('Comandante da Guerra de Troia', 'COMANDANTE DA GUERRA DE TROIA', 'Agamenon', 'AGAMENON', 'MITOLOGIA'),
('Era o deus supremo romano', 'ERA O DEUS SUPREMO ROMANO', 'Júpiter', 'JUPITER', 'MITOLOGIA'),
('Era a deusa da beleza e do amor romana', 'ERA A DEUSA DA BELEZA E DO AMOR ROMANA', 'Vênus', 'VENUS', 'MITOLOGIA'),
('Era o deus do sol egípcio', 'ERA O DEUS DO SOL EGIPCIO', 'Amon-Rá', 'AMONRA', 'MITOLOGIA'),
('Era a deusa do amor e da magia egípcia', 'ERA A DEUSA DO AMOR E DA MAGIA EGIPCIA', 'Ísis', 'ISIS', 'MITOLOGIA'),
('Os povos nórdicos eram os habitantes eram habitantes da atual', 'OS POVOS NORDICOS ERAM OS HABITANTES ERAM HABITANTES DA ATUAL', 'Suécia', 'SUECIA', 'MITOLOGIA'),
('Os povos nórdicos eram os habitantes eram habitantes da atual', 'OS POVOS NORDICOS ERAM OS HABITANTES ERAM HABITANTES DA ATUAL', 'Noruega', 'NORUEGA', 'MITOLOGIA'),
('Os povos nórdicos eram os habitantes eram habitantes da atual', 'OS POVOS NORDICOS ERAM OS HABITANTES ERAM HABITANTES DA ATUAL', 'Dinamarca', 'DINAMARCA', 'MITOLOGIA'),
('Os povos nórdicos eram os habitantes eram habitantes da atual', 'OS POVOS NORDICOS ERAM OS HABITANTES ERAM HABITANTES DA ATUAL', 'Islândia', 'ISLANDIA', 'MITOLOGIA'),
('A casa dos deuses nórdicos', 'A CASA DOS DEUSES NORDICOS', 'Asgard', 'ASGARD', 'MITOLOGIA'),
('Na mitologia nórdica era o governante dos deuses e dos homens', 'NA MITOLOGIA NORDICA ERA O GOVERNANTE DOS DEUSES E DOS HOMENS', 'Odin', 'ODIN', 'MITOLOGIA'),
('Na mitologia nórdica, o comandante do trovão, usava um martelo', 'NA MITOLOGIA NORDICA, O COMANDANTE DO TROVAO, USAVA UM MARTELO', 'Thor', 'THOR', 'MITOLOGIA'),
('Na mitológia nórdica era o deus do fogo; conselheiro e inimigo dos trapaceiros', 'NA MITOLOGIA NORDICA ERA O DEUS DO FOGO; CONSELHEIRO E INIMIGO DOS TRAPACEIROS', 'Loki', 'LOKI', 'MITOLOGIA'),
('Era a deusa do casamento, da família e do nascimento romano', 'ERA A DEUSA DO CASAMENTO, DA FAMILIA E DO NASCIMENTO ROMANO', 'Juno', 'JUNO', 'MITOLOGIA'),
('Era a deusa da sabedoria grega', 'ERA A DEUSA DA SABEDORIA GREGA', 'Atenas', 'ATENAS', 'MITOLOGIA'),
('Era a deusa da sabedoria romana', 'ERA A DEUSA DA SABEDORIA ROMANA', 'Minerva', 'MINERVA', 'MITOLOGIA'),
('Era a deusa do casamento, da família e do nascimento grego', 'ERA A DEUSA DO CASAMENTO, DA FAMILIA E DO NASCIMENTO GREGO', 'Hera', 'HERA', 'MITOLOGIA'),
('Era a deusa da caça e dos animais romano', 'ERA A DEUSA DA CACA E DOS ANIMAIS ROMANO', 'Diana', 'DIANA', 'MITOLOGIA'),
('Era a deusa da caça e dos animais grega', 'ERA A DEUSA DA CACA E DOS ANIMAIS GREGA', 'Artêmis', 'ARTEMIS', 'MITOLOGIA'),
('Era o deus do caos e da escuridão egípcio', 'ERA O DEUS DO CAOS E DA ESCURIDAO EGIPCIO', 'Seth', 'SETH', 'MITOLOGIA'),
('Era o deus dos mortos egípcio', 'ERA O DEUS DOS MORTOS EGIPCIO', 'Anúbis', 'ANUBIS', 'MITOLOGIA'),
('Era o deus da vida egípcio', 'ERA O DEUS DA VIDA EGIPCIO', 'Osíris', 'OSIRIS', 'MITOLOGIA'),
('Religião neopagã com origem na Inglaterra', 'RELIGIAO NEOPAGA COM ORIGEM NA INGLATERRA', 'Wicca', 'WICCA', 'MITOLOGIA'),
('Símbolo pagão mais famoso', 'SIMBOLO PAGAO MAIS FAMOSO', 'Pentagrama', 'PENTAGRAMA', 'MITOLOGIA'),
('O elefante é o animal símbolo deste país', 'O ELEFANTE E O ANIMAL SIMBOLO DESTE PAIS', 'Tailândia', 'TAILANDIA', 'ANIMAIS'),
('O galo é o animal nacional deste país europeu', 'O GALO E O ANIMAL NACIONAL DESTE PAIS EUROPEU', 'França', 'FRANCA', 'ANIMAIS'),
('O animal que é sacrificado nas arenas espanholas', 'O ANIMAL QUE E SACRIFICADO NAS ARENAS ESPANHOLAS', 'Touro', 'TOURO', 'ANIMAIS'),
('O elefante é o animal símbolo deste país', 'O ELEFANTE E O ANIMAL SIMBOLO DESTE PAIS', 'Tailândia', 'TAILANDIA', 'ANIMAIS'),
('O galo é o animal nacional deste país europeu', 'O GALO E O ANIMAL NACIONAL DESTE PAIS EUROPEU', 'França', 'FRANCA', 'ANIMAIS'),
('Mamífero andino com pelagem longa e macia', 'MAMIFERO ANDINO COM PELAGEM LONGA E MACIA', 'Lhama', 'LHAMA', 'ANIMAIS'),
('Animais que possuem o corpo segmentado em anéis', 'ANIMAIS QUE POSSUEM O CORPO SEGMENTADO EM ANEIS', 'Anelídeos', 'ANELIDEOS', 'ANIMAIS'),
('Exemplo de poríferos', 'EXEMPLO DE PORIFEROS', 'Esponja do mar', 'ESPONJA DO MAR', 'ANIMAIS'),
('Exemplos de animal do filo cnidários', 'EXEMPLOS DE ANIMAL DO FILO CNIDARIOS', 'Anêmonas', 'ANEMONAS', 'ANIMAIS'),
('Exemplos de animal do filo asquelmintos', 'EXEMPLOS DE ANIMAL DO FILO ASQUELMINTOS', 'Lombriga', 'LOMBRIGA', 'ANIMAIS'),
('Exemplos de animal do filo molusco', 'EXEMPLOS DE ANIMAL DO FILO MOLUSCO', 'Mexilhão', 'MEXILHAO', 'ANIMAIS'),
('Exemplos de animal do filo molusco', 'EXEMPLOS DE ANIMAL DO FILO MOLUSCO', 'Ostra', 'OSTRA', 'ANIMAIS'),
('Exemplos de animal do filo molusco', 'EXEMPLOS DE ANIMAL DO FILO MOLUSCO', 'Caracóis', 'CARACOIS', 'ANIMAIS'),
('Exemplos de animal do filo anelídeos', 'EXEMPLOS DE ANIMAL DO FILO ANELIDEOS', 'Sanguessuga', 'SANGUESSUGA', 'ANIMAIS'),
('Exemplos de animal do filo anelídeos', 'EXEMPLOS DE ANIMAL DO FILO ANELIDEOS', 'Minhocuçu', 'MINHOCUCU', 'ANIMAIS'),
('Animais que se alimentam de algas e/ou plantas', 'ANIMAIS QUE SE ALIMENTAM DE ALGAS E/OU PLANTAS', 'Herbívoros', 'HERBIVOROS', 'ANIMAIS'),
('Animais que se alimentam tanto de plantas quanto de outros animais', 'ANIMAIS QUE SE ALIMENTAM TANTO DE PLANTAS QUANTO DE OUTROS ANIMAIS', 'Onívoros', 'ONIVOROS', 'ANIMAIS'),
('Animais que se alimentam exclusivamente de outros animais', 'ANIMAIS QUE SE ALIMENTAM EXCLUSIVAMENTE DE OUTROS ANIMAIS', 'Carnívoros', 'CARNIVOROS', 'ANIMAIS'),
('Um dos sobrenomes de Pelé', 'UM DOS SOBRENOMES DE PELE', 'Arantes', 'ARANTES', 'ESPORTES'),
('Substituiu Pelé na Copa do Mundo de 1962', 'SUBSTITUIU PELE NA COPA DO MUNDO DE 1962', 'Amarildo', 'AMARILDO', 'ESPORTES'),
('Filho de Pelé preso em fevereiro de 2017', 'FILHO DE PELE PRESO EM FEVEREIRO DE 2017', 'Edinho', 'EDINHO', 'ESPORTES'),
('Usuário da bicicleta', 'USUARIO DA BICICLETA', 'Ciclista', 'CICLISTA', 'ESPORTES'),
('Esporte de corrida', 'ESPORTE DE CORRIDA', 'Fórmula 1', 'FORMULA 1', 'ESPORTES'),
('Esporte de contato', 'ESPORTE DE CONTATO', 'Boxe', 'BOXE', 'ESPORTES'),
('Esporte praticado no gelo', 'ESPORTE PRATICADO NO GELO', 'Hóquei', 'HOQUEI', 'ESPORTES'),
('Esporte que se utiliza de uma rede', 'ESPORTE QUE SE UTILIZA DE UMA REDE', 'Vôlei', 'VOLEI', 'ESPORTES'),
('Esporte que utiliza praticado em grandes areas', 'ESPORTE QUE UTILIZA PRATICADO EM GRANDES AREAS', 'Golfe', 'GOLFE', 'ESPORTES'),
('Esporte que se utiliza um taco', 'ESPORTE QUE SE UTILIZA UM TACO', 'Beisebol', 'BEISEBOL', 'ESPORTES'),
('Esporte famoso no Brasil.', 'ESPORTE FAMOSO NO BRASIL.', 'Futebol', 'FUTEBOL', 'ESPORTES'),
('Muito praticado na Índia, Reino Unido, Paquistão e Austrália', 'MUITO PRATICADO NA INDIA, REINO UNIDO, PAQUISTAO E AUSTRALIA', 'Críquete', 'CRIQUETE', 'ESPORTES'),
('Esporte mais popular dos  Estados Unidos', 'ESPORTE MAIS POPULAR DOS  ESTADOS UNIDOS', 'Basquete', 'BASQUETE', 'ESPORTES'),
('Local sede das Olimpíadas de 1968', 'LOCAL SEDE DAS OLIMPIADAS DE 1968', 'Cidade do México', 'CIDADE DO MEXICO', 'ESPORTES'),
('O primeiro atleta olímpico brasileiro a conquistar o ouro', 'O PRIMEIRO ATLETA OLIMPICO BRASILEIRO A CONQUISTAR O OURO', 'Guilherme Paraense', 'GUILHERME PARAENSE', 'ESPORTES'),
('Toque dos lábios carinhoso em outra pessoa', 'TOQUE DOS LABIOS CARINHOSO EM OUTRA PESSOA', 'Beijo', 'BEIJO', 'CORPOHUMANO'),
('Inflamação da pele provocada por bactérias', 'INFLAMACAO DA PELE PROVOCADA POR BACTERIAS', 'Piodermite', 'PIODERMITE', 'CORPOHUMANO'),
('Órgão responsável por filtrar o sangue', 'ORGAO RESPONSAVEL POR FILTRAR O SANGUE', 'Fígado', 'FIGADO', 'CORPOHUMANO'),
('Inflamação aguda da pele', 'INFLAMACAO AGUDA DA PELE', 'Psoríase', 'PSORIASE', 'CORPOHUMANO'),
('Cujo contato provoca ardor à pele', 'CUJO CONTATO PROVOCA ARDOR A PELE', 'Urticante', 'URTICANTE', 'CORPOHUMANO'),
('Apontar para estrelas faz isso nascer nos dedos', 'APONTAR PARA ESTRELAS FAZ ISSO NASCER NOS DEDOS', 'Verruga', 'VERRUGA', 'CORPOHUMANO'),
('Músculo do braço entre o ombro e o cotovelo', 'MUSCULO DO BRACO ENTRE O OMBRO E O COTOVELO', 'Bíceps', 'BICEPS', 'CORPOHUMANO'),
('Osso do braco que vai do ombro ao cotovelo', 'OSSO DO BRACO QUE VAI DO OMBRO AO COTOVELO', 'Úmero', 'UMERO', 'CORPOHUMANO'),
('Retém partículas e impede que cheguem ao pulmão', 'RETEM PARTICULAS E IMPEDE QUE CHEGUEM AO PULMAO', 'Traquéia', 'TRAQUEIA', 'CORPOHUMANO'),
('Membrana que envolve o pulmão', 'MEMBRANA QUE ENVOLVE O PULMAO', 'Pleura', 'PLEURA', 'CORPOHUMANO'),
('Cicatrização exagerada da pele', 'CICATRIZACAO EXAGERADA DA PELE', 'Queloide', 'QUELOIDE', 'CORPOHUMANO'),
('Contaminação por larvas de moscas', 'CONTAMINACAO POR LARVAS DE MOSCAS', 'Bicheira', 'BICHEIRA', 'CORPOHUMANO'),
('Consideradas as unidades funcionais e estruturais dos seres vivos', 'CONSIDERADAS AS UNIDADES FUNCIONAIS E ESTRUTURAIS DOS SERES VIVOS', 'Células', 'CELULAS', 'CORPOHUMANO'),
('Apresentam um núcleo definido e organelas membranosas', 'APRESENTAM UM NUCLEO DEFINIDO E ORGANELAS MEMBRANOSAS', 'Eucariontes', 'EUCARIONTES', 'CORPOHUMANO'),
('Um dos 4 tipos básicos de tecidos em nosso corpo', 'UM DOS 4 TIPOS BASICOS DE TECIDOS EM NOSSO CORPO', 'Epitelial', 'EPITELIAL', 'CORPOHUMANO'),
('Um dos 4 tipos básicos de tecidos em nosso corpo', 'UM DOS 4 TIPOS BASICOS DE TECIDOS EM NOSSO CORPO', 'Conjuntivo', 'CONJUNTIVO', 'CORPOHUMANO'),
('Um dos 4 tipos básicos de tecidos em nosso corpo', 'UM DOS 4 TIPOS BASICOS DE TECIDOS EM NOSSO CORPO', 'Muscular', 'MUSCULAR', 'CORPOHUMANO'),
('Um dos 4 tipos básicos de tecidos em nosso corpo', 'UM DOS 4 TIPOS BASICOS DE TECIDOS EM NOSSO CORPO', 'Nervoso', 'NERVOSO', 'CORPOHUMANO'),
('Células que armazenam gorduras', 'CELULAS QUE ARMAZENAM GORDURAS', 'Adipócitos', 'ADIPOCITOS', 'CORPOHUMANO'),
('Células do pâncreas responsáveis por produzir insulina', 'CELULAS DO PANCREAS RESPONSAVEIS POR PRODUZIR INSULINA', 'Beta', 'BETA', 'CORPOHUMANO'),
('Células do fígado que sintetizam proteínas e a bile', 'CELULAS DO FIGADO QUE SINTETIZAM PROTEINAS E A BILE', 'Hepatócitos', 'HEPATOCITOS', 'CORPOHUMANO'),
('Gameta feminino', 'GAMETA FEMININO', 'Ovócito', 'OVOCITO', 'CORPOHUMANO'),
('Faz parte dos membros superiores', 'FAZ PARTE DOS MEMBROS SUPERIORES', 'Braços', 'BRACOS', 'CORPOHUMANO'),
('Faz parte dos membros inferiores', 'FAZ PARTE DOS MEMBROS INFERIORES', 'Pernas', 'PERNAS', 'CORPOHUMANO'),
('Faz parte do tronco', 'FAZ PARTE DO TRONCO', 'Pescoço', 'PESCOCO', 'CORPOHUMANO'),
('Órgão muscular que bombeia o sangue', 'ORGAO MUSCULAR QUE BOMBEIA O SANGUE', 'Coração', 'CORACAO', 'CORPOHUMANO'),
('Órgão esponjoso responsável por oxigenar o sangue.', 'ORGAO ESPONJOSO RESPONSAVEL POR OXIGENAR O SANGUE.', 'Pulmões', 'PULMOES', 'CORPOHUMANO'),
('Órgão mais importante do sistema nervoso', 'ORGAO MAIS IMPORTANTE DO SISTEMA NERVOSO', 'Cérebro', 'CEREBRO', 'CORPOHUMANO'),
('No México conheceu Fidel e Raúl Castro', 'NO MEXICO CONHECEU FIDEL E RAUL CASTRO', 'Che Guevara', 'CHEGUEVARA', 'GEOGRAFIA'),
('Estado americano controlado pelo México antes dos EUA', 'ESTADO AMERICANO CONTROLADO PELO MEXICO ANTES DOS EUA', 'Califórnia', 'CALIFORNIA', 'GEOGRAFIA'),
('Único país das Américas cujo nome começa com M', 'UNICO PAIS DAS AMERICAS CUJO NOME COMECA COM M', 'México', 'MEXICO', 'GEOGRAFIA'),
('Primeiro nome do líder revolucionário mexicando Villa', 'PRIMEIRO NOME DO LIDER REVOLUCIONARIO MEXICANDO VILLA', 'Pancho', 'PANCHO', 'GEOGRAFIA'),
('Capital da Rússia', 'CAPITAL DA RUSSIA', 'Moscou', 'MOSCOU', 'GEOGRAFIA'),
('Nome do primeiro animal a ir ao espaço', 'NOME DO PRIMEIRO ANIMAL A IR AO ESPACO', 'Laika', 'LAIKA', 'GEOGRAFIA'),
('País com o maior número de mortos na 1 Guerra', 'PAIS COM O MAIOR NUMERO DE MORTOS NA 1 GUERRA', 'Rússia', 'RUSSIA', 'GEOGRAFIA'),
('Cidade russa', 'CIDADE RUSSA', 'Cazã', 'CAZA', 'GEOGRAFIA'),
('Cidade russa', 'CIDADE RUSSA', 'Samara', 'SAMARA', 'GEOGRAFIA'),
('Cidade russa', 'CIDADE RUSSA', 'Omsk', 'OMSK', 'GEOGRAFIA'),
('Título dado ao líder russo antes de 1917', 'TITULO DADO AO LIDER RUSSO ANTES DE 1917', 'CzarRússia', 'CZARRUSSIA', 'GEOGRAFIA'),
('Companhia de balé russa', 'COMPANHIA DE BALE RUSSA', 'Bolshoi', 'BOLSHOI', 'GEOGRAFIA'),
('Famosa companhia de balé russa', 'FAMOSA COMPANHIA DE BALE RUSSA', 'Kirov', 'KIROV', 'GEOGRAFIA'),
('Região vendida pela Rússia aos EUA', 'REGIAO VENDIDA PELA RUSSIA AOS EUA', 'Alasca', 'ALASCA', 'GEOGRAFIA'),
('Famoso carro originado na Alemanha', 'FAMOSO CARRO ORIGINADO NA ALEMANHA', 'Fusca', 'FUSCA', 'GEOGRAFIA'),
('País membro do eixo com Itália e Japão na 2 Guerra', 'PAIS MEMBRO DO EIXO COM ITALIA E JAPAO NA 2 GUERRA', 'Alemanha', 'ALEMANHA', 'GEOGRAFIA'),
('Famoso estilista alemão', 'FAMOSO ESTILISTA ALEMAO', 'Karl Lagerfeld', 'KARL LAGERFELD', 'GEOGRAFIA'),
('Cidade onde derrubaram um muro para reunificação da Alemanha', 'CIDADE ONDE DERRUBARAM UM MURO PARA REUNIFICACAO DA ALEMANHA', 'Berlim', 'BERLIM', 'GEOGRAFIA'),
('País que dá nome a um oceano', 'PAIS QUE DA NOME A UM OCEANO', 'Indía', 'INDIA', 'GEOGRAFIA'),
('Capital da Indía', 'CAPITAL DA INDIA', 'Nova Délhi', 'NOVA DELHI', 'GEOGRAFIA'),
('O que as estrelas representam na bandeira brasileira', 'O QUE AS ESTRELAS REPRESENTAM NA BANDEIRA BRASILEIRA', 'Províncias', 'PROVINCIAS', 'GEOGRAFIA'),
('Escândalo recente da política brasileira', 'ESCANDALO RECENTE DA POLITICA BRASILEIRA', 'Mensalão', 'MENSALAO', 'GEOGRAFIA'),
('Menor divisão da moeda oficial brasileira', 'MENOR DIVISAO DA MOEDA OFICIAL BRASILEIRA', 'Centavo', 'CENTAVO', 'GEOGRAFIA'),
('Moeda oficial de Honduras', 'MOEDA OFICIAL DE HONDURAS', 'Lempira', 'LEMPIRA', 'GEOGRAFIA'),
('A moeda oficial dos Tajiques', 'A MOEDA OFICIAL DOS TAJIQUES', 'Somoni', 'SOMONI', 'GEOGRAFIA'),
('A moeda oficial de Moçambique', 'A MOEDA OFICIAL DE MOCAMBIQUE', 'Metical', 'METICAL', 'GEOGRAFIA'),
('Língua oficial de Andorra', 'LINGUA OFICIAL DE ANDORRA', 'Catalão', 'CATALAO', 'GEOGRAFIA'),
('Cidade natal de Madre Teresa de Calcutá', 'CIDADE NATAL DE MADRE TERESA DE CALCUTA', 'Skopje', 'SKOPJE', 'GEOGRAFIA'),
('Grande conquistador francês', 'GRANDE CONQUISTADOR FRANCES', 'Napoleão', 'NAPOLEAO', 'GEOGRAFIA'),
('Região de Hanibal', 'REGIAO DE HANIBAL', 'Cartago', 'CARTAGO', 'GEOGRAFIA'),
('Grande vulcão italiano', 'GRANDE VULCAO ITALIANO', 'Vesuvio', 'VESUVIO', 'GEOGRAFIA'),
('Maior estádio de futebol do Rio de Janeiro', 'MAIOR ESTADIO DE FUTEBOL DO RIO DE JANEIRO', 'Maracanã', 'MARACANA', 'GEOGRAFIA'),
('Maior cidade em extenção no Brasil', 'MAIOR CIDADE EM EXTENCAO NO BRASIL', 'Altamira', 'ALTAMIRA', 'GEOGRAFIA'),
('Cidade mais populosa do Brasil', 'CIDADE MAIS POPULOSA DO BRASIL', 'São Paulo', 'SAO PAULO', 'GEOGRAFIA'),
('Capital do Brasil', 'CAPITAL DO BRASIL', 'Brasília', 'BRASILIA', 'GEOGRAFIA'),
('Antiga capital brasileira', 'ANTIGA CAPITAL BRASILEIRA', 'Rio de Janeiro', 'RIO DE JANEIRO', 'GEOGRAFIA'),
('Falecido', 'FALECIDO', 'Morto', 'MORTO', 'SINONIMOS'),
('Morto', 'MORTO', 'Falecido', 'FALECIDO', 'SINONIMOS'),
('Tabela de serviço', 'TABELA DE SERVICO', 'Escala', 'ESCALA', 'SINONIMOS'),
('Tabela de preços', 'TABELA DE PRECOS', 'Tarifa', 'TARIFA', 'SINONIMOS'),
('Quem professa o paganismo', 'QUEM PROFESSA O PAGANISMO', 'Pagão', 'PAGAO', 'SINONIMOS'),
('Que designa algo não civilizado', 'QUE DESIGNA ALGO NAO CIVILIZADO', 'Bárbaro', 'BARBARO', 'SINONIMOS'),
('Que designa algo não civilizado', 'QUE DESIGNA ALGO NAO CIVILIZADO', 'Primitivo', 'PRIMITIVO', 'SINONIMOS'),
('Impulso para a frente', 'IMPULSO PARA A FRENTE', 'Avanço', 'AVANCO', 'SINONIMOS'),
('Mudança para melhor', 'MUDANCA PARA MELHOR', 'Aperfeiçoamento', 'APERFEICOAMENTO', 'SINONIMOS'),
('Mudança para melhor', 'MUDANCA PARA MELHOR', 'Ampliação', 'AMPLIACAO', 'SINONIMOS'),
('Que tem alegria', 'QUE TEM ALEGRIA', 'Lépido', 'LEPIDO', 'SINONIMOS'),
('Que tem a capacidade de provocar o riso', 'QUE TEM A CAPACIDADE DE PROVOCAR O RISO', 'Jocoso', 'JOCOSO', 'SINONIMOS'),
('Que tem a capacidade de provocar o riso', 'QUE TEM A CAPACIDADE DE PROVOCAR O RISO', 'Cômico', 'COMICO', 'SINONIMOS'),
('Que tem a capacidade de provocar o riso', 'QUE TEM A CAPACIDADE DE PROVOCAR O RISO', 'Folgazão', 'FOLGAZAO', 'SINONIMOS'),
('Que é malicioso', 'QUE E MALICIOSO', 'Solerte', 'SOLERTE', 'SINONIMOS'),
('Que é malicioso', 'QUE E MALICIOSO', 'Taimado', 'TAIMADO', 'SINONIMOS'),
('Que é malicioso', 'QUE E MALICIOSO', 'Velhaco', 'VELHACO', 'SINONIMOS'),
('Que é malicioso', 'QUE E MALICIOSO', 'Finório', 'FINORIO', 'SINONIMOS'),
('Que é malicioso', 'QUE E MALICIOSO', 'Ladino', 'LADINO', 'SINONIMOS'),
('Situado ao lado', 'SITUADO AO LADO', 'Paralelo', 'PARALELO', 'SINONIMOS'),
('Situado ao lado', 'SITUADO AO LADO', 'Colateral', 'COLATERAL', 'SINONIMOS'),
('Reconhecer algo ou alguém', 'RECONHECER ALGO OU ALGUEM', 'Distinguir', 'DISTINGUIR', 'SINONIMOS'),
('Reconhecer algo ou alguém', 'RECONHECER ALGO OU ALGUEM', 'Discernir', 'DISCERNIR', 'SINONIMOS'),
('Gancho terminado em farpa, usado para apanhar peixes', 'GANCHO TERMINADO EM FARPA, USADO PARA APANHAR PEIXES', 'Anzol ', 'ANZOL', 'SINONIMOS'),
('Que não tem piedade', 'QUE NAO TEM PIEDADE', 'Ímpio', 'IMPIO', 'SINONIMOS'),
('Sinal luminoso de trânsito', 'SINAL LUMINOSO DE TRANSITO', 'Farol', 'FAROL', 'SINONIMOS'),
('Cidade de grande importância', 'CIDADE DE GRANDE IMPORTANCIA', 'Metrópole', 'METROPOLE', 'SINONIMOS'),
('Sem valor, sem importancia', 'SEM VALOR, SEM IMPORTANCIA', 'Frivôlo', 'FRIVOLO', 'SINONIMOS'),
('Inexistencia de dor', 'INEXISTENCIA DE DOR', 'Anodinia', 'ANODINIA', 'SINONIMOS'),
('Denguice', 'DENGUICE', 'Manha', 'MANHA', 'SINONIMOS'),
('Moedas de pequeno valor', 'MOEDAS DE PEQUENO VALOR', 'Troco', 'TROCO', 'SINONIMOS'),
('Palavra, gesto, sinal de despedida', 'PALAVRA, GESTO, SINAL DE DESPEDIDA', 'Adeus', 'ADEUS', 'SINONIMOS'),
('A segurança na entrada de um prédio', 'A SEGURANCA NA ENTRADA DE UM PREDIO', 'Portaria', 'PORTARIA', 'SINONIMOS'),
('Arco e flecha em inglês', 'ARCO E FLECHA EM INGLES', 'Archery', 'ARCHERY', 'INGLES'),
('Arremesso de peso em inglês', 'ARREMESSO DE PESO EM INGLES', 'Shot put', 'SHOTPUT', 'INGLES'),
('Automobilismo em inglês', 'AUTOMOBILISMO EM INGLES', 'Motoring', 'MOTORING', 'INGLES'),
('Beisebol em inglês', 'BEISEBOL EM INGLES', 'Baseball', 'BASEBALL', 'INGLES'),
('Boxe em inglês', 'BOXE EM INGLES', 'Boxing', 'BOXING', 'INGLES'),
('Canoagem em inglês', 'CANOAGEM EM INGLES', 'Canoeing', 'CANOEING', 'INGLES'),
('Capoeira em inglês', 'CAPOEIRA EM INGLES', 'Capoeira', 'CAPOEIRA', 'INGLES'),
('Ciclismo em inglês', 'CICLISMO EM INGLES', 'Cycling', 'CYCLING', 'INGLES'),
('Corrida em inglês', 'CORRIDA EM INGLES', 'Race', 'RACE', 'INGLES'),
('Corrida em inglês', 'CORRIDA EM INGLES', 'Sprint', 'SPRINT', 'INGLES'),
('Corrida em inglês', 'CORRIDA EM INGLES', 'Sprint', 'SPRINT', 'INGLES'),
('Críquete em inglês', 'CRIQUETE EM INGLES', 'Cricket', 'CRICKET', 'INGLES'),
('Esgrima em inglês', 'ESGRIMA EM INGLES', 'Fencing', 'FENCING', 'INGLES'),
('Esportes de inverno em inglês', 'ESPORTES DE INVERNO EM INGLES', 'Winter sports', 'WINTERSPORTS', 'INGLES'),
('Futebol americano em inglês', 'FUTEBOL AMERICANO EM INGLES', 'Football', 'FOOTBALL', 'INGLES'),
('Futebol em inglês', 'FUTEBOL EM INGLES', 'Soccer', 'SOCCER', 'INGLES'),
('Ginástica Artística em inglês', 'GINASTICA ARTISTICA EM INGLES', 'Artistic Gymnastics', 'ARTISTICGYMNASTICS', 'INGLES'),
('Golfe em inglês', 'GOLFE EM INGLES', 'Golf', 'GOLF', 'INGLES'),
('Hóquei no gelo em inglês', 'HOQUEI NO GELO EM INGLES', 'Ice hockey', 'ICEHOCKEY', 'INGLES'),
('Handebol em inglês', 'HANDEBOL EM INGLES', 'Handball', 'HANDBALL', 'INGLES'),
('Hipismo em inglês', 'HIPISMO EM INGLES', 'Horse racing', 'HORSERACING', 'INGLES'),
('Judô em inglês', 'JUDO EM INGLES', 'Judo', 'JUDO', 'INGLES'),
('Lançamento de dardo em inglês', 'LANCAMENTO DE DARDO EM INGLES', 'Javelin throw', 'JAVELINTHROW', 'INGLES'),
('Lançamento de disco em inglês', 'LANCAMENTO DE DISCO EM INGLES', 'Discus throw', 'DISCUSTHROW', 'INGLES'),
('Lançamento de martelo em inglês', 'LANCAMENTO DE MARTELO EM INGLES', 'Hammer throw', 'HAMMERTHROW', 'INGLES'),
('Maratona em inglês', 'MARATONA EM INGLES', 'Marathon', 'MARATHON', 'INGLES'),
('Marcha atlética em inglês', 'MARCHA ATLETICA EM INGLES', 'Racewalking', 'RACEWALKING', 'INGLES'),
('Natação em inglês', 'NATACAO EM INGLES', 'Swimming', 'SWIMMING', 'INGLES'),
('Patinação em inglês', 'PATINACAO EM INGLES', 'Roller skating', 'ROLLERSKATING', 'INGLES'),
('Remo em inglês', 'REMO EM INGLES', 'Rowing', 'ROWING', 'INGLES'),
('Salto com vara em inglês', 'SALTO COM VARA EM INGLES', 'Pole Vault', 'POLEVAULT', 'INGLES'),
('Salto em altura em inglês', 'SALTO EM ALTURA EM INGLES', 'High Jump', 'HIGHJUMP', 'INGLES'),
('Salto em distância em inglês', 'SALTO EM DISTANCIA EM INGLES', 'Long jump', 'LONGJUMP', 'INGLES'),
('Salto em distância em inglês', 'SALTO EM DISTANCIA EM INGLES', 'Broad jump', 'BROADJUMP', 'INGLES'),
('Salto triplo em inglês', 'SALTO TRIPLO EM INGLES', 'Triple Jump', 'TRIPLEJUMP', 'INGLES'),
('Tênis em inglês', 'TENIS EM INGLES', 'Tenis', 'TENIS', 'INGLES'),
('Vela em inglês', 'VELA EM INGLES', 'Sailing', 'SAILING', 'INGLES'),
('Voleibol em inglês', 'VOLEIBOL EM INGLES', 'Voleyball', 'VOLEYBALL', 'INGLES'),
('Xadrez em inglês', 'XADREZ EM INGLES', 'Chess', 'CHESS', 'INGLES'),
('Peixe em inglês', 'PEIXE EM INGLES', 'Fish', 'FISH', 'INGLES'),
('Frango em inglês', 'FRANGO EM INGLES', 'Chicken', 'CHICKEN', 'INGLES'),
('Porco em inglês', 'PORCO EM INGLES', 'Pig', 'PIG', 'INGLES'),
('Vaca em inglês', 'VACA EM INGLES', 'Cow', 'COW', 'INGLES'),
('Abelha em inglês', 'ABELHA EM INGLES', 'Bee', 'BEE', 'INGLES'),
('Águia em inglês', 'AGUIA EM INGLES', 'Eagle', 'EAGLE', 'INGLES'),
('Baleia em inglês', 'BALEIA EM INGLES', 'Whale', 'WHALE', 'INGLES'),
('Besouro em inglês', 'BESOURO EM INGLES', 'Beetle', 'BEETLE', 'INGLES'),
('Borboleta em inglês', 'BORBOLETA EM INGLES', 'Butterfly', 'BUTTERFLY', 'INGLES'),
('Cachorro em inglês', 'CACHORRO EM INGLES', 'Dog', 'DOG', 'INGLES'),
('Cavalo em inglês', 'CAVALO EM INGLES', 'Horse', 'HORSE', 'INGLES'),
('Chinchila em inglês', 'CHINCHILA EM INGLES', 'Chinchilla', 'CHINCHILLA', 'INGLES'),
('Cobra em inglês', 'COBRA EM INGLES', 'Snake', 'SNAKE', 'INGLES'),
('Coelho em inglês', 'COELHO EM INGLES', 'Rabbit', 'RABBIT', 'INGLES'),
('Crocodilo em inglês', 'CROCODILO EM INGLES', 'Crocodile', 'CROCODILE', 'INGLES'),
('Dinossauro em inglês', 'DINOSSAURO EM INGLES', 'Dinosaur', 'DINOSAUR', 'INGLES'),
('Elefante em inglês', 'ELEFANTE EM INGLES', 'Elephant', 'ELEPHANT', 'INGLES'),
('Gato em inglês', 'GATO EM INGLES', 'Cat', 'CAT', 'INGLES'),
('Hipopótamo em inglês', 'HIPOPOTAMO EM INGLES', 'Hippopotamus', 'HIPPOPOTAMUS', 'INGLES'),
('Hipopótamo em inglês', 'HIPOPOTAMO EM INGLES', 'Hippo', 'HIPPO', 'INGLES'),
('Leão em inglês', 'LEAO EM INGLES', 'Lion', 'LION', 'INGLES'),
('Macaco em inglês', 'MACACO EM INGLES', 'Monkey', 'MONKEY', 'INGLES'),
('Morcego em inglês', 'MORCEGO EM INGLES', 'Bat', 'BAT', 'INGLES'),
('Mosca em inglês', 'MOSCA EM INGLES', 'Fly', 'FLY', 'INGLES'),
('Mula em inglês', 'MULA EM INGLES', 'Mule', 'MULE', 'INGLES'),
('Pantera em inglês', 'PANTERA EM INGLES', 'Panther', 'PANTHER', 'INGLES'),
('Peixe em inglês', 'PEIXE EM INGLES', 'Fish', 'FISH', 'INGLES'),
('Porco em inglês', 'PORCO EM INGLES', 'Pig', 'PIG', 'INGLES'),
('Pássaro em inglês', 'PASSARO EM INGLES', 'Bird', 'BIRD', 'INGLES'),
('Rato em inglês', 'RATO EM INGLES', 'Mouse', 'MOUSE', 'INGLES'),
('Rato em inglês', 'RATO EM INGLES', 'Rat', 'RAT', 'INGLES'),
('Tartaruga em inglês', 'TARTARUGA EM INGLES', 'Turtle', 'TURTLE', 'INGLES'),
('Tigre em inglês', 'TIGRE EM INGLES', 'Tiger', 'TIGER', 'INGLES'),
('Tubarão em inglês', 'TUBARAO EM INGLES', 'Shark', 'SHARK', 'INGLES'),
('Urso em inglês', 'URSO EM INGLES', 'Bear', 'BEAR', 'INGLES'),
('Vaca em inglês', 'VACA EM INGLES', 'Cow', 'COW', 'INGLES'),
('Zebra em inglês', 'ZEBRA EM INGLES', 'Zebra', 'ZEBRA', 'INGLES'),
('Arbusto em inglês', 'ARBUSTO EM INGLES', 'Bush', 'BUSH', 'INGLES'),
('Arbusto em inglês', 'ARBUSTO EM INGLES', 'Shrub', 'SHRUB', 'INGLES'),
('Arruda em inglês', 'ARRUDA EM INGLES', 'Rue', 'RUE', 'INGLES'),
('Arruda em inglês', 'ARRUDA EM INGLES', 'Herb Grace', 'HERBGRACE', 'INGLES'),
('Árvore em inglês', 'ARVORE EM INGLES', 'Tree', 'TREE', 'INGLES'),
('Azaleia em inglês', 'AZALEIA EM INGLES', 'Azalea', 'AZALEA', 'INGLES'),
('Bromélia em inglês', 'BROMELIA EM INGLES', 'Bromeliads', 'BROMELIADS', 'INGLES'),
('Carvalho em inglês', 'CARVALHO EM INGLES', 'Oak', 'OAK', 'INGLES'),
('Caule em inglês', 'CAULE EM INGLES', 'Stem', 'STEM', 'INGLES'),
('Cebola em inglês', 'CEBOLA EM INGLES', 'Onion', 'ONION', 'INGLES'),
('Erva em inglês', 'ERVA EM INGLES', 'Herb', 'HERB', 'INGLES'),
('Gerânio em inglês', 'GERANIO EM INGLES', 'Geranium', 'GERANIUM', 'INGLES'),
('Girassol em inglês', 'GIRASSOL EM INGLES', 'Sunflower', 'SUNFLOWER', 'INGLES'),
('Grama em inglês', 'GRAMA EM INGLES', 'Grass', 'GRASS', 'INGLES'),
('Lírio em inglês', 'LIRIO EM INGLES', 'Lily', 'LILY', 'INGLES'),
('Margarida em inglês', 'MARGARIDA EM INGLES', 'Daisy', 'DAISY', 'INGLES'),
('Melissa em inglês', 'MELISSA EM INGLES', 'Melissa', 'MELISSA', 'INGLES'),
('Musgo em inglês', 'MUSGO EM INGLES', 'Moss', 'MOSS', 'INGLES'),
('Orquídea em inglês', 'ORQUIDEA EM INGLES', 'Orchid', 'ORCHID', 'INGLES'),
('Papoula em inglês', 'PAPOULA EM INGLES', 'Poppy', 'POPPY', 'INGLES'),
('Pinheiro em inglês', 'PINHEIRO EM INGLES', 'Pine tree', 'PINETREE', 'INGLES'),
('Planta em inglês', 'PLANTA EM INGLES', 'Plant', 'PLANT', 'INGLES'),
('Rosa em inglês', 'ROSA EM INGLES', 'Rose', 'ROSE', 'INGLES'),
('Samambaia em inglês', 'SAMAMBAIA EM INGLES', 'Fern', 'FERN', 'INGLES'),
('Sequóia em inglês', 'SEQUOIA EM INGLES', 'Sequoia', 'SEQUOIA', 'INGLES'),
('Tulipa em inglês', 'TULIPA EM INGLES', 'Tulip', 'TULIP', 'INGLES'),
('Violeta em inglês', 'VIOLETA EM INGLES', 'Violet', 'VIOLET', 'INGLES'),
('Vitória-régia em inglês', 'VITORIA-REGIA EM INGLES', 'Waterlily', 'WATERLILY', 'INGLES'),
('Advogado em inglês', 'ADVOGADO EM INGLES', 'Lawyer', 'LAWYER', 'INGLES'),
('Aeromoça / Comissária de bordo em inglês', 'AEROMOCA / COMISSARIA DE BORDO EM INGLES', 'Flight attendant', 'FLIGHTATTENDANT', 'INGLES'),
('Agente de viagem em inglês', 'AGENTE DE VIAGEM EM INGLES', 'Travel agent', 'TRAVELAGENT', 'INGLES'),
('Analista de Sistemas em inglês', 'ANALISTA DE SISTEMAS EM INGLES', 'Systems Analyst', 'SYSTEMSANALYST', 'INGLES'),
('Arquiteto em inglês', 'ARQUITETO EM INGLES', 'Architect', 'ARCHITECT', 'INGLES'),
('Artista plástico, Pintor em inglês', 'ARTISTA PLASTICO, PINTOR EM INGLES', 'Artist', 'ARTIST', 'INGLES'),
('Atleta em inglês', 'ATLETA EM INGLES', 'Athlete', 'ATHLETE', 'INGLES'),
('Ator em inglês', 'ATOR EM INGLES', 'Actor', 'ACTOR', 'INGLES'),
('Atriz em inglês', 'ATRIZ EM INGLES', 'Actress', 'ACTRESS', 'INGLES'),
('Balconista ou caixa de supermercado em inglês', 'BALCONISTA OU CAIXA DE SUPERMERCADO EM INGLES', 'Grocery clerk', 'GROCERYCLERK', 'INGLES'),
('Bancário em inglês', 'BANCARIO EM INGLES', 'Banker', 'BANKER', 'INGLES'),
('Biólogo em inglês', 'BIOLOGO EM INGLES', 'Biologist', 'BIOLOGIST', 'INGLES'),
('Bibliotecário em inglês', 'BIBLIOTECARIO EM INGLES', 'Librarian', 'LIBRARIAN', 'INGLES'),
('Bombeiro em inglês', 'BOMBEIRO EM INGLES', 'Fireman', 'FIREMAN', 'INGLES'),
('Bombeiro em inglês', 'BOMBEIRO EM INGLES', 'Firefighter', 'FIREFIGHTER', 'INGLES'),
('Cabeleireiro em inglês', 'CABELEIREIRO EM INGLES', 'Hairdresser', 'HAIRDRESSER', 'INGLES'),
('Caixa em inglês', 'CAIXA EM INGLES', 'Cashier', 'CASHIER', 'INGLES'),
('Cantor em inglês', 'CANTOR EM INGLES', 'Singer', 'SINGER', 'INGLES'),
('Carteiro em inglês', 'CARTEIRO EM INGLES', 'Postman', 'POSTMAN', 'INGLES'),
('Carpinteiro em inglês', 'CARPINTEIRO EM INGLES', 'Carpenter', 'CARPENTER', 'INGLES'),
('Carteiro em inglês', 'CARTEIRO EM INGLES', 'Mailman', 'MAILMAN', 'INGLES'),
('Chefe de cozinha em inglês', 'CHEFE DE COZINHA EM INGLES', 'Chef', 'CHEF', 'INGLES'),
('Cientista em inglês', 'CIENTISTA EM INGLES', 'Scientist', 'SCIENTIST', 'INGLES'),
('Comissária de voo, Aeromoça em inglês', 'COMISSARIA DE VOO, AEROMOCA EM INGLES', 'Flight attendant', 'FLIGHTATTENDANT', 'INGLES'),
('Comissário de bordo em inglês', 'COMISSARIO DE BORDO EM INGLES', 'Steward', 'STEWARD', 'INGLES'),
('Consultor em inglês', 'CONSULTOR EM INGLES', 'Consultant', 'CONSULTANT', 'INGLES'),
('Contador em inglês', 'CONTADOR EM INGLES', 'Accountant', 'ACCOUNTANT', 'INGLES'),
('Dançarino / Dançarina em inglês', 'DANCARINO / DANCARINA EM INGLES', 'Dancer', 'DANCER', 'INGLES'),
('Dentista em inglês', 'DENTISTA EM INGLES', 'Dentist', 'DENTIST', 'INGLES'),
('Designer gráfico em inglês', 'DESIGNER GRAFICO EM INGLES', 'Graphic designer', 'GRAPHICDESIGNER', 'INGLES'),
('Detetive em inglês', 'DETETIVE EM INGLES', 'Detective', 'DETECTIVE', 'INGLES'),
('Digitador em inglês', 'DIGITADOR EM INGLES', 'Typist', 'TYPIST', 'INGLES'),
('Dona de casa em inglês', 'DONA DE CASA EM INGLES', 'Housewife', 'HOUSEWIFE', 'INGLES'),
('Doutor em inglês', 'DOUTOR EM INGLES', 'Doctor', 'DOCTOR', 'INGLES'),
('Economista em inglês', 'ECONOMISTA EM INGLES', 'Economist', 'ECONOMIST', 'INGLES'),
('Eletricista em inglês', 'ELETRICISTA EM INGLES', 'Electrician', 'ELECTRICIAN', 'INGLES'),
('Empregada Doméstica em inglês', 'EMPREGADA DOMESTICA EM INGLES', 'Maid', 'MAID', 'INGLES'),
('Encanador em inglês', 'ENCANADOR EM INGLES', 'Plumber', 'PLUMBER', 'INGLES'),
('Enfermeira em inglês', 'ENFERMEIRA EM INGLES', 'Nurse', 'NURSE', 'INGLES'),
('Engenheiro em inglês', 'ENGENHEIRO EM INGLES', 'Engineer', 'ENGINEER', 'INGLES'),
('Escritor em inglês', 'ESCRITOR EM INGLES', 'Writer', 'WRITER', 'INGLES'),
('Esteticista em inglês', 'ESTETICISTA EM INGLES', 'Esthetician', 'ESTHETICIAN', 'INGLES'),
('Esteticista em inglês', 'ESTETICISTA EM INGLES', 'Beautician', 'BEAUTICIAN', 'INGLES'),
('Estudante em inglês', 'ESTUDANTE EM INGLES', 'Student', 'STUDENT', 'INGLES'),
('Executivo em inglês', 'EXECUTIVO EM INGLES', 'Executive', 'EXECUTIVE', 'INGLES'),
('Farmacêutico em inglês', 'FARMACEUTICO EM INGLES', 'Pharmacist', 'PHARMACIST', 'INGLES'),
('Faxineiro em inglês', 'FAXINEIRO EM INGLES', 'Cleaner', 'CLEANER', 'INGLES'),
('Fazendeiro em inglês', 'FAZENDEIRO EM INGLES', 'Farmer', 'FARMER', 'INGLES'),
('Fisioterapeuta em inglês', 'FISIOTERAPEUTA EM INGLES', 'Physical Therapist', 'PHYSICALTHERAPIST', 'INGLES'),
('Fisioterapeuta em inglês', 'FISIOTERAPEUTA EM INGLES', 'Physiotherapist', 'PHYSIOTHERAPIST', 'INGLES'),
('Florista em inglês', 'FLORISTA EM INGLES', 'Florist', 'FLORIST', 'INGLES'),
('Fotógrafo em inglês', 'FOTOGRAFO EM INGLES', 'Photographer', 'PHOTOGRAPHER', 'INGLES'),
('Garçom em inglês', 'GARCOM EM INGLES', 'Waiter', 'WAITER', 'INGLES'),
('Garçonete em inglês', 'GARCONETE EM INGLES', 'Waitress', 'WAITRESS', 'INGLES'),
('Gerente em inglês', 'GERENTE EM INGLES', 'Manager', 'MANAGER', 'INGLES'),
('Guia em inglês', 'GUIA EM INGLES', 'Guide', 'GUIDE', 'INGLES'),
('Homem de negócios / Empresário em inglês', 'HOMEM DE NEGOCIOS / EMPRESARIO EM INGLES', 'Businessman', 'BUSINESSMAN', 'INGLES'),
('Instrutor em inglês', 'INSTRUTOR EM INGLES', 'Instructor', 'INSTRUCTOR', 'INGLES'),
('Intérprete em inglês', 'INTERPRETE EM INGLES', 'Interpreter', 'INTERPRETER', 'INGLES'),
('Investigador em inglês', 'INVESTIGADOR EM INGLES', 'Investigator', 'INVESTIGATOR', 'INGLES'),
('Jardineiro em inglês', 'JARDINEIRO EM INGLES', 'Gardener', 'GARDENER', 'INGLES'),
('Joalheiro em inglês', 'JOALHEIRO EM INGLES', 'Jeweler', 'JEWELER', 'INGLES'),
('Jogador em inglês', 'JOGADOR EM INGLES', 'Player', 'PLAYER', 'INGLES'),
('Jornalista em inglês', 'JORNALISTA EM INGLES', 'Journalist', 'JOURNALIST', 'INGLES'),
('Juiz em inglês', 'JUIZ EM INGLES', 'Judge', 'JUDGE', 'INGLES'),
('Leiteiro em inglês', 'LEITEIRO EM INGLES', 'Milkman', 'MILKMAN', 'INGLES'),
('Lixeiro em inglês', 'LIXEIRO EM INGLES', 'Garbage Collector', 'GARBAGECOLLECTOR', 'INGLES'),
('Lixeiro em inglês', 'LIXEIRO EM INGLES', 'Garbageman', 'GARBAGEMAN', 'INGLES'),
('Locutor em inglês', 'LOCUTOR EM INGLES', 'Broadcaster', 'BROADCASTER', 'INGLES'),
('Médico em inglês', 'MEDICO EM INGLES', 'Physician', 'PHYSICIAN', 'INGLES'),
('Médico em inglês', 'MEDICO EM INGLES', 'Doctor', 'DOCTOR', 'INGLES'),
('Músico em inglês', 'MUSICO EM INGLES', 'Musician', 'MUSICIAN', 'INGLES'),
('Maquiador em inglês', 'MAQUIADOR EM INGLES', 'Makeup Artist', 'MAKEUPARTIST', 'INGLES'),
('Marinheiro em inglês', 'MARINHEIRO EM INGLES', 'Mariner', 'MARINER', 'INGLES'),
('Mecânico em inglês', 'MECANICO EM INGLES', 'Mechanic', 'MECHANIC', 'INGLES'),
('Motorista em inglês', 'MOTORISTA EM INGLES', 'Driver', 'DRIVER', 'INGLES'),
('Mulher de negócios / Empresária em inglês', 'MULHER DE NEGOCIOS / EMPRESARIA EM INGLES', 'Businesswoman', 'BUSINESSWOMAN', 'INGLES'),
('Nutricionista / Terapeuta Nutricional em inglês', 'NUTRICIONISTA / TERAPEUTA NUTRICIONAL EM INGLES', 'Nutritional Therapist', 'NUTRITIONALTHERAPIST', 'INGLES'),
('Operador em inglês', 'OPERADOR EM INGLES', 'Operator', 'OPERATOR', 'INGLES'),
('Padeiro em inglês', 'PADEIRO EM INGLES', 'Baker', 'BAKER', 'INGLES'),
('Paramédico em inglês', 'PARAMEDICO EM INGLES', 'Paramedic', 'PARAMEDIC', 'INGLES'),
('Pedreiro em inglês', 'PEDREIRO EM INGLES', 'Bricklayer', 'BRICKLAYER', 'INGLES'),
('Pedreiro em inglês', 'PEDREIRO EM INGLES', 'Maison', 'MAISON', 'INGLES'),
('Pescador em inglês', 'PESCADOR EM INGLES', 'Fisherman', 'FISHERMAN', 'INGLES'),
('Pianista em inglês', 'PIANISTA EM INGLES', 'Pianist', 'PIANIST', 'INGLES'),
('Piloto em inglês', 'PILOTO EM INGLES', 'Pilot', 'PILOT', 'INGLES'),
('Pintor em inglês', 'PINTOR EM INGLES', 'Painter', 'PAINTER', 'INGLES'),
('Podólogo em inglês', 'PODOLOGO EM INGLES', 'Podiatrist', 'PODIATRIST', 'INGLES'),
('Político em inglês', 'POLITICO EM INGLES', 'Politician', 'POLITICIAN', 'INGLES'),
('Professor de escola em inglês', 'PROFESSOR DE ESCOLA EM INGLES', 'Teacher', 'TEACHER', 'INGLES'),
('Professor de faculdade em inglês', 'PROFESSOR DE FACULDADE EM INGLES', 'Professor', 'PROFESSOR', 'INGLES'),
('Programador de computadores em inglês', 'PROGRAMADOR DE COMPUTADORES EM INGLES', 'Computer programmer', 'COMPUTERPROGRAMMER', 'INGLES'),
('Recepcionista em inglês', 'RECEPCIONISTA EM INGLES', 'Receptionist', 'RECEPTIONIST', 'INGLES'),
('Repórter em inglês', 'REPORTER EM INGLES', 'Reporter', 'REPORTER', 'INGLES'),
('Salva-vidas em inglês', 'SALVA-VIDAS EM INGLES', 'Bodyguard', 'BODYGUARD', 'INGLES'),
('Salva-vidas em inglês', 'SALVA-VIDAS EM INGLES', 'Lifeguard', 'LIFEGUARD', 'INGLES'),
('Secretária em inglês', 'SECRETARIA EM INGLES', 'Secretary', 'SECRETARY', 'INGLES'),
('Soldado em inglês', 'SOLDADO EM INGLES', 'Soldier', 'SOLDIER', 'INGLES'),
('Taxista em inglês', 'TAXISTA EM INGLES', 'Cab Driver', 'CABDRIVER', 'INGLES'),
('Tradutor em inglês', 'TRADUTOR EM INGLES', 'Translator', 'TRANSLATOR', 'INGLES'),
('Vendedor de loja em inglês', 'VENDEDOR DE LOJA EM INGLES', 'Salesperson', 'SALESPERSON', 'INGLES'),
('Vendedora em inglês', 'VENDEDORA EM INGLES', 'Saleswoman', 'SALESWOMAN', 'INGLES'),
('Vendedor em inglês', 'VENDEDOR EM INGLES', 'Salesman', 'SALESMAN', 'INGLES'),
('Zelador em inglês', 'ZELADOR EM INGLES', 'Janitor', 'JANITOR', 'INGLES'),
('Abelha em espanhol', 'ABELHA EM ESPANHOL', 'Abeja', 'ABEJA', 'ESPANHOL'),
('Águia em espanhol', 'AGUIA EM ESPANHOL', 'Águila', 'AGUILA', 'ESPANHOL'),
('Aranha em espanhol', 'ARANHA EM ESPANHOL', 'Araña', 'ARANA', 'ESPANHOL'),
('Avestruz em espanhol', 'AVESTRUZ EM ESPANHOL', 'Avestruz', 'AVESTRUZ', 'ESPANHOL'),
('Baleia em espanhol', 'BALEIA EM ESPANHOL', 'Ballena', 'BALLENA', 'ESPANHOL'),
('Barata em espanhol', 'BARATA EM ESPANHOL', 'Cucaracha', 'CUCARACHA', 'ESPANHOL'),
('Bode em espanhol', 'BODE EM ESPANHOL', 'Chivo', 'CHIVO', 'ESPANHOL'),
('Boi em espanhol', 'BOI EM ESPANHOL', 'Buey', 'BUEY', 'ESPANHOL'),
('Borboleta em espanhol', 'BORBOLETA EM ESPANHOL', 'Mariposa', 'MARIPOSA', 'ESPANHOL'),
('Búfalo em espanhol', 'BUFALO EM ESPANHOL', 'Búfalo', 'BUFALO', 'ESPANHOL'),
('Cavalo em espanhol', 'CAVALO EM ESPANHOL', 'Caballo', 'CABALLO', 'ESPANHOL'),
('Cabra em espanhol', 'CABRA EM ESPANHOL', 'Cabra', 'CABRA', 'ESPANHOL'),
('Cachorro em espanhol', 'CACHORRO EM ESPANHOL', 'Perro', 'PERRO', 'ESPANHOL'),
('Camelo em espanhol', 'CAMELO EM ESPANHOL', 'Camello', 'CAMELLO', 'ESPANHOL'),
('Canguru em espanhol', 'CANGURU EM ESPANHOL', 'Canguro', 'CANGURO', 'ESPANHOL'),
('Caranguejo em espanhol', 'CARANGUEJO EM ESPANHOL', 'Cangrejo', 'CANGREJO', 'ESPANHOL'),
('Cegonha em espanhol', 'CEGONHA EM ESPANHOL', 'Cigüeña', 'CIGUENA', 'ESPANHOL'),
('Chimpanzé em espanhol', 'CHIMPANZE EM ESPANHOL', 'Chimpancé', 'CHIMPANCE', 'ESPANHOL'),
('Codorna em espanhol', 'CODORNA EM ESPANHOL', 'Codorniz', 'CODORNIZ', 'ESPANHOL'),
('Coelho em espanhol', 'COELHO EM ESPANHOL', 'Conejo', 'CONEJO', 'ESPANHOL'),
('Coruja em espanhol', 'CORUJA EM ESPANHOL', 'Búho', 'BUHO', 'ESPANHOL'),
('Coruja em espanhol', 'CORUJA EM ESPANHOL', 'Lechuza', 'LECHUZA', 'ESPANHOL'),
('Crocodilo em espanhol', 'CROCODILO EM ESPANHOL', 'Cocodrilo', 'COCODRILO', 'ESPANHOL'),
('Dinossauro em espanhol', 'DINOSSAURO EM ESPANHOL', 'Dinosaurio', 'DINOSAURIO', 'ESPANHOL'),
('Dragão em espanhol', 'DRAGAO EM ESPANHOL', 'Dragón', 'DRAGON', 'ESPANHOL'),
('Elefante em espanhol', 'ELEFANTE EM ESPANHOL', 'Elefante', 'ELEFANTE', 'ESPANHOL'),
('Estrela-do-mar em espanhol', 'ESTRELA-DO-MAR EM ESPANHOL', 'Estrellamar', 'ESTRELLAMAR', 'ESPANHOL'),
('Foca em espanhol', 'FOCA EM ESPANHOL', 'Foca', 'FOCA', 'ESPANHOL'),
('Formiga em espanhol', 'FORMIGA EM ESPANHOL', 'Hormiga', 'HORMIGA', 'ESPANHOL'),
('Frango em espanhol', 'FRANGO EM ESPANHOL', 'Pollo', 'POLLO', 'ESPANHOL'),
('Gaivota em espanhol', 'GAIVOTA EM ESPANHOL', 'Gaviota', 'GAVIOTA', 'ESPANHOL'),
('Galo em espanhol', 'GALO EM ESPANHOL', 'Gallo', 'GALLO', 'ESPANHOL'),
('Galinha em espanhol', 'GALINHA EM ESPANHOL', 'Gallina', 'GALLINA', 'ESPANHOL'),
('Gato em espanhol', 'GATO EM ESPANHOL', 'Gato', 'GATO', 'ESPANHOL'),
('Girafa em espanhol', 'GIRAFA EM ESPANHOL', 'Jirafa', 'JIRAFA', 'ESPANHOL'),
('Golfinho em espanhol', 'GOLFINHO EM ESPANHOL', 'Delfín', 'DELFIN', 'ESPANHOL'),
('Grilo em espanhol', 'GRILO EM ESPANHOL', 'Grillo', 'GRILLO', 'ESPANHOL'),
('Hipopótamo em espanhol', 'HIPOPOTAMO EM ESPANHOL', 'Hipopótamo', 'HIPOPOTAMO', 'ESPANHOL'),
('Jacaré em espanhol', 'JACARE EM ESPANHOL', 'Caimán', 'CAIMAN', 'ESPANHOL'),
('Jacaré em espanhol', 'JACARE EM ESPANHOL', 'Yacaré', 'YACARE', 'ESPANHOL'),
('Javali em espanhol', 'JAVALI EM ESPANHOL', 'Jabalí', 'JABALI', 'ESPANHOL'),
('Joaninha em espanhol', 'JOANINHA EM ESPANHOL', 'Mariquita', 'MARIQUITA', 'ESPANHOL'),
('Lagosta em espanhol', 'LAGOSTA EM ESPANHOL', 'Langosta', 'LANGOSTA', 'ESPANHOL'),
('Leão em espanhol', 'LEAO EM ESPANHOL', 'León', 'LEON', 'ESPANHOL'),
('Lombriga em espanhol', 'LOMBRIGA EM ESPANHOL', 'Lombriz', 'LOMBRIZ', 'ESPANHOL'),
('Macaco em espanhol', 'MACACO EM ESPANHOL', 'Macaco', 'MACACO', 'ESPANHOL'),
('Macaco em espanhol', 'MACACO EM ESPANHOL', 'Mono', 'MONO', 'ESPANHOL'),
('Mosca em espanhol', 'MOSCA EM ESPANHOL', 'Mosca', 'MOSCA', 'ESPANHOL'),
('Mosquito em espanhol', 'MOSQUITO EM ESPANHOL', 'Mosquito', 'MOSQUITO', 'ESPANHOL'),
('Morcego em espanhol', 'MORCEGO EM ESPANHOL', 'Murciélago', 'MURCIELAGO', 'ESPANHOL'),
('Onça em espanhol', 'ONCA EM ESPANHOL', 'Onza', 'ONZA', 'ESPANHOL'),
('Ovelha em espanhol', 'OVELHA EM ESPANHOL', 'Oveja', 'OVEJA', 'ESPANHOL'),
('Pássaro em espanhol', 'PASSARO EM ESPANHOL', 'Pájaro', 'PAJARO', 'ESPANHOL'),
('Pato em espanhol', 'PATO EM ESPANHOL', 'Pato', 'PATO', 'ESPANHOL'),
('Peixe em espanhol', 'PEIXE EM ESPANHOL', 'Pez', 'PEZ', 'ESPANHOL'),
('Pinguim em espanhol', 'PINGUIM EM ESPANHOL', 'Pingüino', 'PINGÜINO', 'ESPANHOL'),
('Pomba em espanhol', 'POMBA EM ESPANHOL', 'Paloma', 'PALOMA', 'ESPANHOL'),
('Porco em espanhol', 'PORCO EM ESPANHOL', 'Puerco', 'PUERCO', 'ESPANHOL'),
('Rato em espanhol', 'RATO EM ESPANHOL', 'Ratón', 'RATON', 'ESPANHOL'),
('Sapo em espanhol', 'SAPO EM ESPANHOL', 'Sapo', 'SAPO', 'ESPANHOL'),
('Tartaruga em espanhol', 'TARTARUGA EM ESPANHOL', 'Tortuga', 'TORTUGA', 'ESPANHOL'),
('Tigre em espanhol', 'TIGRE EM ESPANHOL', 'Tigre', 'TIGRE', 'ESPANHOL'),
('Touro em espanhol', 'TOURO EM ESPANHOL', 'Toro', 'TORO', 'ESPANHOL'),
('Urso em espanhol', 'URSO EM ESPANHOL', 'Oso', 'OSO', 'ESPANHOL'),
('Vaca em espanhol', 'VACA EM ESPANHOL', 'Vaca', 'VACA', 'ESPANHOL'),
('Zebra em espanhol', 'ZEBRA EM ESPANHOL', 'Cebra', 'CEBRA', 'ESPANHOL'),
('Antebraço em espanhol', 'ANTEBRACO EM ESPANHOL', 'Antebrazo', 'ANTEBRAZO', 'ESPANHOL'),
('Axila em espanhol', 'AXILA EM ESPANHOL', 'Axila', 'AXILA', 'ESPANHOL'),
('Barriga em espanhol', 'BARRIGA EM ESPANHOL', 'Barriga', 'BARRIGA', 'ESPANHOL'),
('Boca em espanhol', 'BOCA EM ESPANHOL', 'Boca', 'BOCA', 'ESPANHOL'),
('Bochecha em espanhol', 'BOCHECHA EM ESPANHOL', 'Mejilla', 'MEJILLA', 'ESPANHOL'),
('Braço em espanhol', 'BRACO EM ESPANHOL', 'Brazo', 'BRAZO', 'ESPANHOL'),
('Cabeça em espanhol', 'CABECA EM ESPANHOL', 'Cabeza', 'CABEZA', 'ESPANHOL'),
('Cabelo em espanhol', 'CABELO EM ESPANHOL', 'Cabello', 'CABELLO', 'ESPANHOL'),
('Cabelo em espanhol', 'CABELO EM ESPANHOL', 'Pelo', 'PELO', 'ESPANHOL'),
('Cílios em espanhol', 'CILIOS EM ESPANHOL', 'Pestañas', 'PESTANAS', 'ESPANHOL'),
('Cintura em espanhol', 'CINTURA EM ESPANHOL', 'Cintura', 'CINTURA', 'ESPANHOL'),
('Coluna em espanhol', 'COLUNA EM ESPANHOL', 'Columna', 'COLUMNA', 'ESPANHOL'),
('Coração em espanhol', 'CORACAO EM ESPANHOL', 'Corazón', 'CORAZON', 'ESPANHOL'),
('Costelas em espanhol', 'COSTELAS EM ESPANHOL', 'Costillas', 'COSTILLAS', 'ESPANHOL'),
('Cotovelo em espanhol', 'COTOVELO EM ESPANHOL', 'Codo', 'CODO', 'ESPANHOL'),
('Coxa em espanhol', 'COXA EM ESPANHOL', 'Muslo', 'MUSLO', 'ESPANHOL'),
('Dentes em espanhol', 'DENTES EM ESPANHOL', 'Dientes', 'DIENTES', 'ESPANHOL'),
('Garganta em espanhol', 'GARGANTA EM ESPANHOL', 'Garganta', 'GARGANTA', 'ESPANHOL'),
('Joelho em espanhol', 'JOELHO EM ESPANHOL', 'Rodilla', 'RODILLA', 'ESPANHOL'),
('Lábios em espanhol', 'LABIOS EM ESPANHOL', 'Labios', 'LABIOS', 'ESPANHOL'),
('Língua em espanhol', 'LINGUA EM ESPANHOL', 'Lengua', 'LENGUA', 'ESPANHOL'),
('Mão em espanhol', 'MAO EM ESPANHOL', 'Mano', 'MANO', 'ESPANHOL'),
('Nádegas em espanhol', 'NADEGAS EM ESPANHOL', 'Nalgas', 'NALGAS', 'ESPANHOL'),
('Nariz em espanhol', 'NARIZ EM ESPANHOL', 'Nariz', 'NARIZ', 'ESPANHOL'),
('Olhos em espanhol', 'OLHOS EM ESPANHOL', 'Ojos', 'OJOS', 'ESPANHOL'),
('Orelha em espanhol', 'ORELHA EM ESPANHOL', 'Oreja', 'OREJA', 'ESPANHOL'),
('Ouvido em espanhol', 'OUVIDO EM ESPANHOL', 'Oído', 'OIDO', 'ESPANHOL'),
('Ossos em espanhol', 'OSSOS EM ESPANHOL', 'Huesos', 'HUESOS', 'ESPANHOL'),
('Pé em espanhol', 'PE EM ESPANHOL', 'Pie', 'PIE', 'ESPANHOL'),
('Peito em espanhol', 'PEITO EM ESPANHOL', 'Pecho', 'PECHO', 'ESPANHOL'),
('Pele em espanhol', 'PELE EM ESPANHOL', 'Piel', 'PIEL', 'ESPANHOL'),
('Perna em espanhol', 'PERNA EM ESPANHOL', 'Pierna', 'PIERNA', 'ESPANHOL'),
('Pescoço em espanhol', 'PESCOCO EM ESPANHOL', 'Cuello', 'CUELLO', 'ESPANHOL'),
('Pulmão em espanhol', 'PULMAO EM ESPANHOL', 'Pulmón', 'PULMON', 'ESPANHOL'),
('Pulso em espanhol', 'PULSO EM ESPANHOL', 'Muñeca', 'MUNECA', 'ESPANHOL'),
('Queixo em espanhol', 'QUEIXO EM ESPANHOL', 'Mentón', 'MENTON', 'ESPANHOL'),
('Queixo em espanhol', 'QUEIXO EM ESPANHOL', 'Barbilla', 'BARBILLA', 'ESPANHOL'),
('Seios em espanhol', 'SEIOS EM ESPANHOL', 'Senos', 'SENOS', 'ESPANHOL'),
('Sobrancelha em espanhol', 'SOBRANCELHA EM ESPANHOL', 'Ceja', 'CEJA', 'ESPANHOL'),
('Testa em espanhol', 'TESTA EM ESPANHOL', 'Frente', 'FRENTE', 'ESPANHOL'),
('Tornozelo em espanhol', 'TORNOZELO EM ESPANHOL', 'Tobillo', 'TOBILLO', 'ESPANHOL'),
('Umbigo em espanhol', 'UMBIGO EM ESPANHOL', 'Ombligo', 'OMBLIGO', 'ESPANHOL'),
('Unha em espanhol', 'UNHA EM ESPANHOL', 'Uña', 'UNA', 'ESPANHOL'),
('Gato em francês', 'GATO EM FRANCES', 'Le chat', 'LECHAT', 'FRANCES'),
('Cão em francês', 'CAO EM FRANCES', 'Le chien', 'LECHIEN', 'FRANCES'),
('Furão em francês', 'FURAO EM FRANCES', 'Le furet', 'LEFURET', 'FRANCES'),
('Peixe-dourado em francês', 'PEIXE-DOURADO EM FRANCES', 'Le poisson rouge', 'LEPOISSONROUGE', 'FRANCES'),
('Gerbil (rato do deserto) em francês', 'GERBIL (RATO DO DESERTO) EM FRANCES', 'La gerbille', 'LAGERBILLE', 'FRANCES'),
('Hamster em francês', 'HAMSTER EM FRANCES', 'Le hamster', 'LEHAMSTER', 'FRANCES'),
('lhama em francês', 'LHAMA EM FRANCES', 'Le lama', 'LELAMA', 'FRANCES'),
('Papagaio em francês', 'PAPAGAIO EM FRANCES', 'Le perroquet', 'LEPERROQUET', 'FRANCES'),
('Coelho em francês', 'COELHO EM FRANCES', 'Le lapin', 'LELAPIN', 'FRANCES'),
('Rato em francês', 'RATO EM FRANCES', 'La souris', 'LASOURIS', 'FRANCES'),
('Formiga em francês', 'FORMIGA EM FRANCES', 'La fourmi', 'LAFOURMI', 'FRANCES'),
('Abelha em francês', 'ABELHA EM FRANCES', 'L’abeille', 'LABEILLE', 'FRANCES'),
('Borboleta em francês', 'BORBOLETA EM FRANCES', 'Le papillon', 'LEPAPILLON', 'FRANCES'),
('Barata em francês', 'BARATA EM FRANCES', 'Le cafard', 'LECAFARD', 'FRANCES'),
('Caracol em francês', 'CARACOL EM FRANCES', 'L’escargot', 'LESCARGOT', 'FRANCES'),
('Aranha em francês', 'ARANHA EM FRANCES', 'L’araignée', 'LARAIGNEE', 'FRANCES'),
('Gafanhoto em francês', 'GAFANHOTO EM FRANCES', 'La sauterelle', 'LASAUTERELLE', 'FRANCES'),
('Grilo em francês', 'GRILO EM FRANCES', 'Le cricket', 'LECRICKET', 'FRANCES'),
('Louva a deus em francês', 'LOUVA A DEUS EM FRANCES', 'La mante', 'LAMANTE', 'FRANCES'),
('Galinha em francês', 'GALINHA EM FRANCES', 'Le poulet', 'LEPOULET', 'FRANCES'),
('Vaca em francês', 'VACA EM FRANCES', 'La vache', 'LAVACHE', 'FRANCES'),
('Burro em francês', 'BURRO EM FRANCES', 'L’âne', 'LANE', 'FRANCES'),
('Ganso em francês', 'GANSO EM FRANCES', 'L’oie', 'LOIE', 'FRANCES'),
('Cavalo em francês', 'CAVALO EM FRANCES', 'Le cheval', 'LECHEVAL', 'FRANCES'),
('Cabra em francês', 'CABRA EM FRANCES', 'La chèvre', 'LACHEVRE', 'FRANCES'),
('Mula em francês', 'MULA EM FRANCES', 'La mule', 'LAMULE', 'FRANCES'),
('Porco em francês', 'PORCO EM FRANCES', 'Le cochon', 'LECOCHON', 'FRANCES'),
('Ovelha em francês', 'OVELHA EM FRANCES', 'Le mouton', 'LEMOUTON', 'FRANCES'),
('Jacaré em francês', 'JACARE EM FRANCES', 'L’alligator', 'LALLIGATOR', 'FRANCES'),
('Crocodilo em francês', 'CROCODILO EM FRANCES', 'Le crocodile', 'LECROCODILE', 'FRANCES'),
('Rã em francês', 'RA EM FRANCES', 'La grenouille', 'LAGRENOUILLE', 'FRANCES'),
('Largato em francês', 'LARGATO EM FRANCES', 'Le lézard', 'LELEZARD', 'FRANCES'),
('Serpente em francês', 'SERPENTE EM FRANCES', 'Le serpent', 'LESERPENT', 'FRANCES'),
('Sapo em francês', 'SAPO EM FRANCES', 'Le crapaud', 'LECRAPAUD', 'FRANCES'),
('Tartaruga em francês', 'TARTARUGA EM FRANCES', 'La tortue', 'LATORTUE', 'FRANCES'),
('Advogado em francês', 'ADVOGADO EM FRANCES', 'Avocat', 'AVOCAT', 'FRANCES'),
('Agricultor em francês', 'AGRICULTOR EM FRANCES', 'Agriculteur', 'AGRICULTEUR', 'FRANCES'),
('Alpinista em francês', 'ALPINISTA EM FRANCES', 'Alpiniste', 'ALPINISTE', 'FRANCES'),
('Aluno em francês', 'ALUNO EM FRANCES', 'Èleve', 'ELEVE', 'FRANCES'),
('Aluno em francês', 'ALUNO EM FRANCES', 'Étudiant', 'ETUDIANT', 'FRANCES'),
('Árbitro em francês', 'ARBITRO EM FRANCES', 'Juge', 'JUGE', 'FRANCES'),
('Árbitro em francês', 'ARBITRO EM FRANCES', 'Arbitre', 'ARBITRE', 'FRANCES'),
('Astronauta em francês', 'ASTRONAUTA EM FRANCES', 'Astronaute', 'ASTRONAUTE', 'FRANCES'),
('Ator em francês', 'ATOR EM FRANCES', 'Acteur', 'ACTEUR', 'FRANCES'),
('Atriz em francês', 'ATRIZ EM FRANCES', 'Actrice', 'ACTRICE', 'FRANCES'),
('Administrador em francês', 'ADMINISTRADOR EM FRANCES', 'Administrateur', 'ADMINISTRATEUR', 'FRANCES'),
('Administradora em francês', 'ADMINISTRADORA EM FRANCES', 'Administratrice', 'ADMINISTRATRICE', 'FRANCES'),
('Arquiteto em francês', 'ARQUITETO EM FRANCES', 'Architecte', 'ARCHITECTE', 'FRANCES'),
('Bancário em francês', 'BANCARIO EM FRANCES', 'Bancaire', 'BANCAIRE', 'FRANCES'),
('Barbeiro em francês', 'BARBEIRO EM FRANCES', 'Coiffeur', 'COIFFEUR', 'FRANCES'),
('Bombeiro em francês', 'BOMBEIRO EM FRANCES', 'Sapeur-pompier', 'SAPEURPOMPIER', 'FRANCES'),
('Cabeleireiro em francês', 'CABELEIREIRO EM FRANCES', 'Coiffeur', 'COIFFEUR', 'FRANCES'),
('Camionista em francês', 'CAMIONISTA EM FRANCES', 'Camionneur', 'CAMIONNEUR', 'FRANCES'),
('Cantor em francês', 'CANTOR EM FRANCES', 'Chanteur', 'CHANTEUR', 'FRANCES'),
('Cantora em francês', 'CANTORA EM FRANCES', 'Chanteuse', 'CHANTEUSE', 'FRANCES'),
('Comentador Desportivo em francês', 'COMENTADOR DESPORTIVO EM FRANCES', 'Commentateur Sportif', 'COMMENTATEURSPORTIF', 'FRANCES'),
('Comentador Político em francês', 'COMENTADOR POLITICO EM FRANCES', 'Commentateur Politique', 'COMMENTATEURPOLITIQUE', 'FRANCES'),
('Condutor em francês', 'CONDUTOR EM FRANCES', 'Conducteur', 'CONDUCTEUR', 'FRANCES'),
('Controlador aéreo em francês', 'CONTROLADOR AEREO EM FRANCES', 'Contrôleur Aérien', 'CONTROLEURAERIEN', 'FRANCES'),
('Corretor de bolsa em francês', 'CORRETOR DE BOLSA EM FRANCES', 'Courtier en Bourse', 'COURTIERENBOURSE', 'FRANCES'),
('Cozinheiro em francês', 'COZINHEIRO EM FRANCES', 'Cuisinier', 'CUISINIER', 'FRANCES'),
('Cozinheiro-chefe em francês', 'COZINHEIRO-CHEFE EM FRANCES', 'Chef', 'CHEF', 'FRANCES'),
('Cientista em francês', 'CIENTISTA EM FRANCES', 'Scientifique', 'SCIENTIFIQUE', 'FRANCES'),
('Compositor em francês', 'COMPOSITOR EM FRANCES', 'Compositeur', 'COMPOSITEUR', 'FRANCES'),
('Confeiteiro em francês', 'CONFEITEIRO EM FRANCES', 'Confiseur', 'CONFISEUR', 'FRANCES'),
('Contabilista em francês', 'CONTABILISTA EM FRANCES', 'Comptable', 'COMPTABLE', 'FRANCES'),
('Costureira em francês', 'COSTUREIRA EM FRANCES', 'Couturière', 'COUTURIERE', 'FRANCES'),
('Dançarino em francês', 'DANCARINO EM FRANCES', 'Danseur', 'DANSEUR', 'FRANCES'),
('Dentista em francês', 'DENTISTA EM FRANCES', 'Dentiste', 'DENTISTE', 'FRANCES'),
('Diretor em francês', 'DIRETOR EM FRANCES', 'Directeur', 'DIRECTEUR', 'FRANCES'),
('Distribuidor em francês', 'DISTRIBUIDOR EM FRANCES', 'Distributeur', 'DISTRIBUTEUR', 'FRANCES'),
('Dona de Casa / Doméstica em francês', 'DONA DE CASA / DOMESTICA EM FRANCES', 'Ménagere', 'MENAGERE', 'FRANCES'),
('Economista em francês', 'ECONOMISTA EM FRANCES', 'Economiste', 'ECONOMISTE', 'FRANCES'),
('Eletricista em francês', 'ELETRICISTA EM FRANCES', 'Electricien', 'ELECTRICIEN', 'FRANCES'),
('Empregado de Mesa em francês', 'EMPREGADO DE MESA EM FRANCES', 'Garçon', 'GARCON', 'FRANCES'),
('Enfermeira em francês', 'ENFERMEIRA EM FRANCES', 'Infirmière', 'INFIRMIERE', 'FRANCES'),
('Engenheiro em francês', 'ENGENHEIRO EM FRANCES', 'Ingénieur', 'INGENIEUR', 'FRANCES'),
('Engraxador em francês', 'ENGRAXADOR EM FRANCES', 'Cireur de chaussures', 'CIREURDECHAUSSURES', 'FRANCES'),
('Escritor em francês', 'ESCRITOR EM FRANCES', 'Ècrivain', 'ECRIVAIN', 'FRANCES'),
('Esteticista em francês', 'ESTETICISTA EM FRANCES', 'Esthéticien', 'ESTHETICIEN', 'FRANCES'),
('Estudante em francês', 'ESTUDANTE EM FRANCES', 'Etudiant', 'ETUDIANT', 'FRANCES'),
('Florista em francês', 'FLORISTA EM FRANCES', 'Fleuriste', 'FLEURISTE', 'FRANCES'),
('Funcionária de escritório em francês', 'FUNCIONARIA DE ESCRITORIO EM FRANCES', 'Employé de bureau', 'EMPLOYEDEBUREAU', 'FRANCES'),
('Funcionário Público em francês', 'FUNCIONARIO PUBLICO EM FRANCES', 'Officiel du Gouvernement', 'OFFICIELDUGOUVERNEMENT', 'FRANCES'),
('Futebolista em francês', 'FUTEBOLISTA EM FRANCES', 'Footballeur', 'FOOTBALLEUR', 'FRANCES'),
('Investigador em francês', 'INVESTIGADOR EM FRANCES', 'Investigateur', 'INVESTIGATEUR', 'FRANCES'),
('Jogador de Futebol em francês', 'JOGADOR DE FUTEBOL EM FRANCES', 'Joueur de football', 'JOUEURDEFOOTBALL', 'FRANCES'),
('Jornalista em francês', 'JORNALISTA EM FRANCES', 'Journaliste', 'JOURNALISTE', 'FRANCES'),
('Juíz em francês', 'JUIZ EM FRANCES', 'Juge', 'JUGE', 'FRANCES'),
('Lixeiro em francês', 'LIXEIRO EM FRANCES', 'Corbeille', 'CORBEILLE', 'FRANCES'),
('Lojista em francês', 'LOJISTA EM FRANCES', 'Commerçant', 'COMMERCANT', 'FRANCES'),
('Manicure em francês', 'MANICURE EM FRANCES', 'Manucure', 'MANUCURE', 'FRANCES'),
('Maquinista em francês', 'MAQUINISTA EM FRANCES', 'Mécanicienne', 'MECANICIENNE', 'FRANCES'),
('Mecânico em francês', 'MECANICO EM FRANCES', 'Mécanicien', 'MECANICIEN', 'FRANCES'),
('Mediador de Seguros em francês', 'MEDIADOR DE SEGUROS EM FRANCES', 'Courtier d''assurance', 'COURTIERDASSURANCE', 'FRANCES'),
('Médico em francês', 'MEDICO EM FRANCES', 'Médecin', 'MEDECIN', 'FRANCES'),
('Merceeiro em francês', 'MERCEEIRO EM FRANCES', 'Epicier', 'EPICIER', 'FRANCES'),
('Militar em francês', 'MILITAR EM FRANCES', 'Militaire', 'MILITAIRE', 'FRANCES'),
('Modelo em francês', 'MODELO EM FRANCES', 'Modèle', 'MODELE', 'FRANCES'),
('Músico em francês', 'MUSICO EM FRANCES', 'Musicien', 'MUSICIEN', 'FRANCES'),
('Músico em francês', 'MUSICO EM FRANCES', 'Musicienne', 'MUSICIENNE', 'FRANCES'),
('Oftalmologista em francês', 'OFTALMOLOGISTA EM FRANCES', 'Ophtalmologiste', 'OPHTALMOLOGISTE', 'FRANCES'),
('Operador de caixa em francês', 'OPERADOR DE CAIXA EM FRANCES', 'Caissier', 'CAISSIER', 'FRANCES'),
('Ourives em francês', 'OURIVES EM FRANCES', 'Orfèvre', 'ORFEVRE', 'FRANCES'),
('Padeiro em francês', 'PADEIRO EM FRANCES', 'Boulanger', 'BOULANGER', 'FRANCES'),
('Pedicure em francês', 'PEDICURE EM FRANCES', 'Pédicure', 'PEDICURE', 'FRANCES'),
('Pedreiro em francês', 'PEDREIRO EM FRANCES', 'Maçon', 'MACON', 'FRANCES'),
('Peixeiro em francês', 'PEIXEIRO EM FRANCES', 'Poissonnerie', 'POISSONNERIE', 'FRANCES'),
('Pianista em francês', 'PIANISTA EM FRANCES', 'Pianiste', 'PIANISTE', 'FRANCES'),
('Picheleiro/Canalizador em francês', 'PICHELEIRO/CANALIZADOR EM FRANCES', 'Plombier', 'PLOMBIER', 'FRANCES'),
('Pintor em francês', 'PINTOR EM FRANCES', 'Peintre', 'PEINTRE', 'FRANCES'),
('Polícia em francês', 'POLICIA EM FRANCES', 'Police', 'POLICE', 'FRANCES'),
('Político em francês', 'POLITICO EM FRANCES', 'Politique', 'POLITIQUE', 'FRANCES'),
('Presidente da Câmara em francês', 'PRESIDENTE DA CAMARA EM FRANCES', 'Maire', 'MAIRE', 'FRANCES'),
('Professor em francês', 'PROFESSOR EM FRANCES', 'Professeur', 'PROFESSEUR', 'FRANCES'),
('Professor universitário em francês', 'PROFESSOR UNIVERSITARIO EM FRANCES', 'Professeur d''université', 'PROFESSEURDUNIVERSITE', 'FRANCES'),
('Profissional de Marketing em francês', 'PROFISSIONAL DE MARKETING EM FRANCES', 'Pprofessionnel du Marketing', 'PPROFESSIONNELDUMARKETING', 'FRANCES'),
('Programador em francês', 'PROGRAMADOR EM FRANCES', 'Programmeur', 'PROGRAMMEUR', 'FRANCES'),
('Psicólogo em francês', 'PSICOLOGO EM FRANCES', 'Psychologue', 'PSYCHOLOGUE', 'FRANCES'),
('Recepcionista em francês', 'RECEPCIONISTA EM FRANCES', 'Réceptionniste', 'RECEPTIONNISTE', 'FRANCES'),
('Sapateiro em francês', 'SAPATEIRO EM FRANCES', 'Cordonnier', 'CORDONNIER', 'FRANCES'),
('Secretária Administrativa em francês', 'SECRETARIA ADMINISTRATIVA EM FRANCES', 'Secrétaire Administratif', 'SECRETAIREADMINISTRATIF', 'FRANCES'),
('Segurança em francês', 'SEGURANCA EM FRANCES', 'Sécurité', 'SECURITE', 'FRANCES'),
('Açougueiro em francês', 'ACOUGUEIRO EM FRANCES', 'Boucher', 'BOUCHER', 'FRANCES'),
('Técnico em francês', 'TECNICO EM FRANCES', 'Technicien', 'TECHNICIEN', 'FRANCES'),
('Técnico de Laboratório em francês', 'TECNICO DE LABORATORIO EM FRANCES', 'Technicienne de Laboratoire', 'TECHNICIENNEDELABORATOIRE', 'FRANCES'),
('Técnico de Segurança em francês', 'TECNICO DE SEGURANCA EM FRANCES', 'Technicien de sécurité', 'TECHNICIENDESECURITE', 'FRANCES'),
('Telefonista em francês', 'TELEFONISTA EM FRANCES', 'Opérateur', 'OPERATEUR', 'FRANCES'),
('Tradutor em francês', 'TRADUTOR EM FRANCES', 'Traducteur', 'TRADUCTEUR', 'FRANCES'),
('Treinador em francês', 'TREINADOR EM FRANCES', 'Entraîneur', 'ENTRAINEUR', 'FRANCES'),
('Varredor de Rua em francês', 'VARREDOR DE RUA EM FRANCES', 'Balayeur', 'BALAYEUR', 'FRANCES'),
('Vendedor em francês', 'VENDEDOR EM FRANCES', 'Vendeur', 'VENDEUR', 'FRANCES'),
('Veterinário em francês', 'VETERINARIO EM FRANCES', 'Vétérinaire', 'VETERINAIRE', 'FRANCES');

INSERT INTO Palavras (Valor, ValorSemAcento, Dica, DicaSemAcento, CategoriaID)
SELECT 
	'Boxe' AS Valor, 
	'BOXE' AS ValorSemAcento, 
	'Esporte de contato' AS Dica, 
	'ESPORTE DE CONTATO' AS DicaSemAcento,
	(SELECT ID FROM Categorias WHERE DescricaoSemAcento = 'ESPORTES' LIMIT 1) AS CategoriaID
WHERE NOT EXISTS (
	SELECT 1 FROM Palavras 
	WHERE ValorSemAcento = 'BOXE' AND DicaSemAcento = 'ESPORTE DE CONTATO'
);

-- Inserindo valores
INSERT INTO Palavras (Valor, ValorSemAcento, Dica, DicaSemAcento, CategoriaID)
SELECT 
	p.Valor, 
	p.ValorSemAcento, 
	p.Dica, 
	p.DicaSemAcento,
	c.ID AS CategoriaID
FROM _Palavras p
INNER JOIN Categorias c ON c.DescricaoSemAcento = p.Categoria
EXCEPT
SELECT 
	pp.Valor, 
	pp.ValorSemAcento, 
	pp.Dica, 
	pp.DicaSemAcento, 
	pp.CategoriaID
FROM Palavras pp;
