---------------------------------------------
------------- Tables #2 ---------------------
---------------------------------------------

DROP TABLE IF EXISTS public."Jogos";
DROP TABLE IF EXISTS public."Pontuacoes";

-- Table: public.Jogos

CREATE TABLE IF NOT EXISTS public."Jogos"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Codigo" integer,
    "Descricao" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Jogos" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_Jogos_Codigo" UNIQUE ("Codigo")
) TABLESPACE pg_default;

-- Table: public.Pontuacoes

CREATE TABLE IF NOT EXISTS public."Pontuacoes"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),    
    "JogoID" integer,
	"AutorID" integer,
    "Itens" integer,
	"Pontos" integer,
	"Erros" integer,
	"DataJogo" timestamp without time zone,
    CONSTRAINT "PK_Pontuacoes" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Pontuacoes_Jogos_JogoID" FOREIGN KEY ("JogoID")
        REFERENCES public."Jogos" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Pontuacoes_Usuarios_AutorID" FOREIGN KEY ("AutorID")
        REFERENCES public."Usuarios" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
) TABLESPACE pg_default;

ALTER TABLE public."Jogos"
    OWNER to postgres;

ALTER TABLE public."Pontuacoes"
    OWNER to postgres;

-----------------------------------------------
-------------- Index --------------------------
-----------------------------------------------

-- Index: IX_Pontuacoes_JogoID

DROP INDEX IF EXISTS public."IX_Pontuacoes_JogoID";

CREATE INDEX IF NOT EXISTS "IX_Pontuacoes_JogoID"
    ON public."Pontuacoes" USING btree
    ("JogoID" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_Pontuacoes_AutorID

DROP INDEX IF EXISTS public."IX_Pontuacoes_AutorID";

CREATE INDEX IF NOT EXISTS "IX_Pontuacoes_AutorID"
    ON public."Pontuacoes" USING btree
    ("AutorID" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_Pontuacoes_DataJogo

DROP INDEX IF EXISTS public."IX_Pontuacoes_DataJogo";

CREATE INDEX IF NOT EXISTS "IX_Pontuacoes_DataJogo"
    ON public."Pontuacoes" USING btree
    ("DataJogo" ASC NULLS LAST)
    TABLESPACE pg_default;
