---------------------------------------------
-------------- Tables -----------------------
---------------------------------------------

DROP TABLE IF EXISTS public."Sessoes";
DROP TABLE IF EXISTS public."CruzadaItens";
DROP TABLE IF EXISTS public."Cruzadas";
DROP TABLE IF EXISTS public."Usuarios";
DROP TABLE IF EXISTS public."Palavras";
DROP TABLE IF EXISTS public."Categorias";

-- Table: public.Categorias

CREATE TABLE IF NOT EXISTS public."Categorias"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Descricao" text COLLATE pg_catalog."default",
    "DescricaoSemAcento" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_Categorias_DescricaoSemAcento" UNIQUE ("DescricaoSemAcento")
) TABLESPACE pg_default;

-- Table: public.Palavras

CREATE TABLE IF NOT EXISTS public."Palavras"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Valor" text COLLATE pg_catalog."default",
    "Dica" text COLLATE pg_catalog."default",
    "CategoriaID" integer,
    "SerieEscolar" integer,
    "DicaSemAcento" text COLLATE pg_catalog."default",
    "ValorSemAcento" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Palavras" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_Palavras_ValorSemAcento_DicaSemAcento" UNIQUE ("ValorSemAcento", "DicaSemAcento"),
    CONSTRAINT "FK_Palavras_Categorias_CategoriaID" FOREIGN KEY ("CategoriaID")
        REFERENCES public."Categorias" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
) TABLESPACE pg_default;

-- Table: public.Usuarios

CREATE TABLE IF NOT EXISTS public."Usuarios"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Email" text COLLATE pg_catalog."default",
    "Nome" text COLLATE pg_catalog."default",
    "Senha" text COLLATE pg_catalog."default",
    "Perfil" integer NOT NULL,
    "Idade" integer,
    "Sexo" integer,
    "SerieEscolar" integer,
    "Disciplina" text COLLATE pg_catalog."default",
    "DicaSecreta" text COLLATE pg_catalog."default",
    "PalavraSecreta" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("ID")
) TABLESPACE pg_default;

-- Table: public.Cruzadas

CREATE TABLE IF NOT EXISTS public."Cruzadas"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TamanhoX" integer NOT NULL,
    "TamanhoY" integer NOT NULL,
    "Criacao" timestamp without time zone NOT NULL,
    "AutorID" integer,
    "CategoriaID" integer,
    CONSTRAINT "PK_Cruzadas" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Cruzadas_Categorias_CategoriaID" FOREIGN KEY ("CategoriaID")
        REFERENCES public."Categorias" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Cruzadas_Usuarios_AutorID" FOREIGN KEY ("AutorID")
        REFERENCES public."Usuarios" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
) TABLESPACE pg_default;

-- Table: public.CruzadaItens

CREATE TABLE IF NOT EXISTS public."CruzadaItens"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PalavraID" integer,
    "PosicaoX" integer NOT NULL,
    "PosicaoY" integer NOT NULL,
    "Orientacao" integer NOT NULL,
    "CruzadaID" integer,
    CONSTRAINT "PK_CruzadaItens" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CruzadaItens_Cruzadas_CruzadaID" FOREIGN KEY ("CruzadaID")
        REFERENCES public."Cruzadas" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_CruzadaItens_Palavras_PalavraID" FOREIGN KEY ("PalavraID")
        REFERENCES public."Palavras" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
) TABLESPACE pg_default;

-- Table: public.Sessoes

CREATE TABLE IF NOT EXISTS public."Sessoes"
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Inicio" timestamp without time zone NOT NULL,
    "Fim" timestamp without time zone,
    "CruzadaID" integer,
    "Acertos" integer,
    "UsuarioID" integer,
    CONSTRAINT "PK_Sessoes" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Sessoes_Cruzadas_CruzadaID" FOREIGN KEY ("CruzadaID")
        REFERENCES public."Cruzadas" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_Sessoes_Usuarios_UsuarioID" FOREIGN KEY ("UsuarioID")
        REFERENCES public."Usuarios" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
) TABLESPACE pg_default;

ALTER TABLE public."Categorias"
    OWNER to postgres;

ALTER TABLE public."Palavras"
    OWNER to postgres;

ALTER TABLE public."Usuarios"
    OWNER to postgres;

ALTER TABLE public."Cruzadas"
    OWNER to postgres;

ALTER TABLE public."CruzadaItens"
    OWNER to postgres;

ALTER TABLE public."Sessoes"
    OWNER to postgres;

-----------------------------------------------
-------------- Index --------------------------
-----------------------------------------------

-- Index: IX_Palavras_CategoriaID

DROP INDEX IF EXISTS public."IX_Palavras_CategoriaID";

CREATE INDEX IF NOT EXISTS "IX_Palavras_CategoriaID"
    ON public."Palavras" USING btree
    ("CategoriaID" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_Usuarios_Email_Nome

DROP INDEX IF EXISTS public."IX_Usuarios_Email_Nome";

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Usuarios_Email_Nome"
    ON public."Usuarios" USING btree
    ("Email" COLLATE pg_catalog."default" ASC NULLS LAST, "Nome" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_Cruzadas_AutorID

DROP INDEX IF EXISTS public."IX_Cruzadas_AutorID";

CREATE INDEX IF NOT EXISTS "IX_Cruzadas_AutorID"
    ON public."Cruzadas" USING btree
    ("AutorID" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_Cruzadas_CategoriaID

DROP INDEX IF EXISTS public."IX_Cruzadas_CategoriaID";

CREATE INDEX IF NOT EXISTS "IX_Cruzadas_CategoriaID"
    ON public."Cruzadas" USING btree
    ("CategoriaID" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_CruzadaItens_CruzadaID

DROP INDEX IF EXISTS public."IX_CruzadaItens_CruzadaID";

CREATE INDEX IF NOT EXISTS "IX_CruzadaItens_CruzadaID"
    ON public."CruzadaItens" USING btree
    ("CruzadaID" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_CruzadaItens_PalavraID

DROP INDEX IF EXISTS public."IX_CruzadaItens_PalavraID";

CREATE INDEX IF NOT EXISTS "IX_CruzadaItens_PalavraID"
    ON public."CruzadaItens" USING btree
    ("PalavraID" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: IX_Sessoes_CruzadaID

DROP INDEX IF EXISTS public."IX_Sessoes_CruzadaID";

CREATE INDEX IF NOT EXISTS "IX_Sessoes_CruzadaID"
    ON public."Sessoes" USING btree
    ("CruzadaID" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Sessoes_UsuarioID

DROP INDEX IF EXISTS public."IX_Sessoes_UsuarioID";

CREATE INDEX IF NOT EXISTS "IX_Sessoes_UsuarioID"
    ON public."Sessoes" USING btree
    ("UsuarioID" ASC NULLS LAST)
    TABLESPACE pg_default;
