-- MySQL Script generated by MySQL Workbench
-- sáb 02 out 2021 18:38:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integrador` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `integrador` ;

-- -----------------------------------------------------
-- Table `integrador`.`Categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador`.`Categorias` ;

CREATE TABLE IF NOT EXISTS `integrador`.`Categorias` (
  `ID` INT NOT NULL,
  `Descricao` VARCHAR(100) NULL,
  `DescricaoSemAcento` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DescricaoSemAcento_UNIQUE` (`DescricaoSemAcento` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`CruzadaItens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador`.`CruzadaItens` ;

CREATE TABLE IF NOT EXISTS `integrador`.`CruzadaItens` (
  `ID` INT NOT NULL,
  `PalavraID` INT NULL,
  `PosicaoX` INT NULL DEFAULT 0,
  `PosicaoY` INT NULL DEFAULT 0,
  `Orientacao` INT NULL DEFAULT 0,
  `CruzadaID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_CRUZADAITEM_CRUZADA_idx` (`CruzadaID` ASC) VISIBLE,
  INDEX `FK_CRUZADAITEM_PALAVRA_idx` (`PalavraID` ASC) VISIBLE,
  CONSTRAINT `FK_CRUZADAITEM_CRUZADA`
    FOREIGN KEY (`CruzadaID`)
    REFERENCES `integrador`.`Cruzadas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CRUZADAITEM_PALAVRA`
    FOREIGN KEY (`PalavraID`)
    REFERENCES `integrador`.`Palavras` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`Cruzadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador`.`Cruzadas` ;

CREATE TABLE IF NOT EXISTS `integrador`.`Cruzadas` (
  `ID` INT NOT NULL,
  `TamanhoX` INT NULL,
  `TamanhoY` INT NULL,
  `Criacao` DATETIME NULL,
  `AutorID` INT NULL,
  `CategoriaID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_CRUZADA_AUTOR_idx` (`AutorID` ASC) VISIBLE,
  INDEX `FK_CRUZADA_CATEGORIA_idx` (`CategoriaID` ASC) VISIBLE,
  CONSTRAINT `FK_CRUZADA_AUTOR`
    FOREIGN KEY (`AutorID`)
    REFERENCES `integrador`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CRUZADA_CATEGORIA`
    FOREIGN KEY (`CategoriaID`)
    REFERENCES `integrador`.`Categorias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`Palavras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador`.`Palavras` ;

CREATE TABLE IF NOT EXISTS `integrador`.`Palavras` (
  `ID` INT NOT NULL,
  `Valor` VARCHAR(100) NULL,
  `Dica` VARCHAR(1000) NULL,
  `SerieEscolar` INT NULL DEFAULT NULL,
  `CategoriaID` INT NULL,
  `ValorSemAcento` VARCHAR(100) NULL,
  `DicaSemAcento` VARCHAR(1000) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `UQ_VALOR_Dica` (`ValorSemAcento` ASC, `DicaSemAcento` ASC) VISIBLE,
  CONSTRAINT `FK_PALAVRA_CATEGORIA`
    FOREIGN KEY (`ID`)
    REFERENCES `integrador`.`Categorias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`Sessoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador`.`Sessoes` ;

CREATE TABLE IF NOT EXISTS `integrador`.`Sessoes` (
  `ID` INT NOT NULL,
  `Inicio` DATETIME NULL DEFAULT NULL,
  `Fim` DATETIME NULL DEFAULT NULL,
  `CruzadaID` INT NULL DEFAULT NULL,
  `Acertos` INT NULL DEFAULT NULL,
  `UsuarioID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `integrador`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `integrador`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `integrador`.`Usuarios` (
  `ID` INT NOT NULL,
  `Email` VARCHAR(20) NULL,
  `Nome` VARCHAR(100) NULL,
  `Senha` VARCHAR(100) NULL,
  `Perfil` INT NULL DEFAULT 0,
  `DicaSecreta` VARCHAR(50) NULL DEFAULT NULL,
  `PalavraSecreta` VARCHAR(50) NULL DEFAULT NULL,
  `Idade` INT NULL DEFAULT NULL,
  `Sexo` INT NULL DEFAULT NULL,
  `SerieEscolar` INT NULL DEFAULT NULL,
  `Disciplina` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
